### ISSUE TITLE
Error running npm install

### ISSUE THREAD

**Issue by yehezkel** [getsentry/sentry-cli#104]
while running npm install sentry-cli the follow exception gets thrown:

>npm install sentry-cli
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> sentry-cli@0.0.4 postinstall /home/areyes/web/sentry/node_modules/sentry-cli
> node tasks/download.js

Start downloading jar at http://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone/2.2.1/wiremock-standalone-2.2.1.jar
/home/areyes/web/sentry/node_modules/sentry-cli/tasks/download.js:72
      var progress = log.newItem(url, length);
                         ^

TypeError: log.newItem is not a function
    at Request.<anonymous> (/home/areyes/web/sentry/node_modules/sentry-cli/tasks/download.js:72:26)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestResponse (/home/areyes/web/sentry/node_modules/request/request.js:954:10)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
npm WARN sentry@1.0.0 No description
npm WARN sentry@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sentry-cli@0.0.4 postinstall: `node tasks/download.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sentry-cli@0.0.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/areyes/.npm/_logs/2017-08-08T15_23_22_569Z-debug.log

**Comment by mitsuhiko** [comment]
`npm install sentry-cli` is incorrect, the correct command is `npm install sentry-cli-binary`. We do not control the sentry-cli package on npm.
