### ISSUE TITLE
TypeError: log.newItem is not a function when installing

### ISSUE THREAD

**Issue by FredyC** [getsentry/sentry-cli#131]
Just tried to install this with NPM 5.3.0 globally and got this error. Installation failed.

[2017-10-08T11_47_23_439Z-debug.log](https://github.com/getsentry/sentry-cli/files/1366841/2017-10-08T11_47_23_439Z-debug.log)

Looking into log file, I see different error there, so I am attaching output from console as well.

```
D:\workspace>npm i -g sentry-cli
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
D:\users\DarkMaster\AppData\Roaming\npm\sentry-cli -> D:\users\DarkMaster\AppData\Roaming\npm\node_modules\sentry-cli\bin\sentry-cli

> sentry-cli@0.0.4 postinstall D:\users\DarkMaster\AppData\Roaming\npm\node_modules\sentry-cli
> node tasks/download.js

Start downloading jar at http://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone/2.2.1/wiremock-standalone-2.2.1.jar
D:\users\DarkMaster\AppData\Roaming\npm\node_modules\sentry-cli\tasks\download.js:72
      var progress = log.newItem(url, length);
                         ^

TypeError: log.newItem is not a function
    at Request.<anonymous> (D:\users\DarkMaster\AppData\Roaming\npm\node_modules\sentry-cli\tasks\download.js:72:26)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.onRequestResponse (D:\users\DarkMaster\AppData\Roaming\npm\node_modules\sentry-cli\node_modules\request\request.js:954:10)
    at emitOne (events.js:120:20)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at Socket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sentry-cli@0.0.4 postinstall: `node tasks/download.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sentry-cli@0.0.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\users\DarkMaster\AppData\Roaming\npm-cache\_logs\2017-10-08T11_47_23_439Z-debug.log
```

**Comment by FredyC** [comment]
Hmm, nevermind, haven't realized it's actually published under different module name. That's kinda annoying that regular name was stolen by someone else :(

**Comment by sseetals** [comment]
Just a note that the package name is "sentry"
