### ISSUE TITLE
Command failed in docker

### ISSUE THREAD

**Issue by kmuu011** [getsentry/sentry-cli#1315]
Hello, i using 2.5.2 version on docker
and.. using m1 mac book pro

This does not work only in the docker

```
Error: Command failed: sentry-cli releases new -p nestjs_boilerplate nestJS_boilerplate@0.0.3 --org violet-cf --auth-token 64024e576c5-----------------------------------
node_0  | /home/nestjs/app/node_modules/@sentry/cli/sentry-cli: 2: /home/nestjs/app/node_modules/@sentry/cli/sentry-cli: Syntax error: word unexpected (expecting ")")
node_0  | 
node_0  |     at ChildProcess.exithandler (child_process.js:308:12)
node_0  |     at ChildProcess.emit (events.js:315:20)
node_0  |     at ChildProcess.EventEmitter.emit (domain.js:486:12)
node_0  |     at maybeClose (internal/child_process.js:1048:16)
node_0  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
node_0  |   killed: false,
node_0  |   code: 2,
node_0  |   signal: null,
node_0  |   cmd: 'sentry-cli releases new -p nestjs_boilerplate nestJS_boilerplate@0.0.3 --org violet-cf --auth-token 64024e576c5d491691------------'
```

But it works well if manually run the command inside the Docker container or not use docker 

Please solve my problem 

Thank you

**Comment by kamilogorek** [comment]
You are copying binary that was built on a different architecture (your mac, `arm64`, and trying to run it inside the docker container (which is `x86`). You need to install the CLI directly inside the docker instead. See https://github.com/getsentry/sentry-cli/issues/1317 for more details.
