### ISSUE TITLE
EAGAIN when attempting to use local in Bazel Build

### ISSUE THREAD

**Issue by marsh73** [getsentry/sentry-cli#1588]
### Environment

```
Bazel
  BAZEL_BINDIR=bazel-out/darwin_arm64-fastbuild/bin \
    BAZEL_BUILD_FILE_PATH=web/web-ui/BUILD.bazel \
    BAZEL_COMPILATION_MODE=fastbuild \
    BAZEL_PACKAGE=web/web-ui \
    BAZEL_TARGET=//web/web-ui:.aspect_rules_js/node_modules/@sentry+cli@1.75.0/lc \
    BAZEL_TARGET_CPU=darwin_arm64 \
    BAZEL_TARGET_NAME=.aspect_rules_js/node_modules/@sentry+cli@1.75.0/lc \
    BAZEL_WORKSPACE=tecton_monorepo \
    JS_BINARY__PATCH_NODE_FS=1 \
    JS_BINARY__SILENT_ON_SUCCESS=1 \
    JS_BINARY__USE_EXECROOT_ENTRY_POINT=1 \
    PATH=/bin:/usr/bin:/usr/local/bin \
```

### What version are you running? Etc.

```
@sentry/webpack-plugin 1.20.0
@sentry/cli 1.75.0
```

### Steps to Reproduce

running bazel build without any ENV flags, works locally but not in buildkite, because sentry-cli lifecycle hooks is attempting to create a directory in the root, which is not allowed, and not what we would want.

when attempting to pass the `SENTRYCLI_USE_LOCAL=1` with the build i get the following 

```
Error: spawn /private/var/tmp/_bazel_justinmarshall/bd58c2fcd0ab26e2c0c8e9140e8db35c/execroot/tecton_monorepo/bazel-out/darwin_arm64-fastbuild/bin/web/web-ui/node_modules/.aspect_rules_js/@sentry+cli@1.75.0/node_modules/@sentry/cli/sentry-cli EAGAIN
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -35,
  code: 'EAGAIN',
  syscall: 'spawn /private/var/tmp/_bazel_justinmarshall/bd58c2fcd0ab26e2c0c8e9140e8db35c/execroot/tecton_monorepo/bazel-out/darwin_arm64-fastbuild/bin/web/web-ui/node_modules/.aspect_rules_js/@sentry+cli@1.75.0/node_modules/@sentry/cli/sentry-cli',
  path: '/private/var/tmp/_bazel_justinmarshall/bd58c2fcd0ab26e2c0c8e9140e8db35c/execroot/tecton_monorepo/bazel-out/darwin_arm64-fastbuild/bin/web/web-ui/node_modules/.aspect_rules_js/@sentry+cli@1.75.0/node_modules/@sentry/cli/sentry-cli',
  spawnargs: [ '--version' ]
}


> @sentry/cli@1.75.0 install /private/var/tmp/_bazel_justinmarshall/bd58c2fcd0ab26e2c0c8e9140e8db35c/execroot/tecton_monorepo/bazel-out/darwin_arm64-fastbuild/bin/web/web-ui/node_modules/.aspect_rules_js/@sentry+cli@1.75.0/node_modules/@sentry/cli
> node ./scripts/install.js

===============================================================
Failure while running lifecycle hook for package '@sentry/cli@1.75.0':

  Script:  'install'
  Command: `node ./scripts/install.js`

Stack trace:

Exit status 1
    at EventEmitter.<anonymous> (/private/var/tmp/_bazel_justinmarshall/bd58c2fcd0ab26e2c0c8e9140e8db35c/execroot/tecton_monorepo/bazel-out/darwin_arm64-fastbuild/bin/external/aspect_rules_js/npm/private/lifecycle/min/index.min.js:47:92054)
    at EventEmitter.emit (node:events:390:28)
    at ChildProcess.<anonymous> (/private/var/tmp/_bazel_justinmarshall/bd58c2fcd0ab26e2c0c8e9140e8db35c/execroot/tecton_monorepo/bazel-out/darwin_arm64-fastbuild/bin/external/aspect_rules_js/npm/private/lifecycle/min/index.min.js:1:195024)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

I ran this to check that the sentry-cli package was available 

```
$ /private/var/tmp/_bazel_justinmarshall/bd58c2fcd0ab26e2c0c8e9140e8db35c/execroot/tecton_monorepo/web/web-ui/node_modules/@sentry/cli/sentry-cli --version
sentry-cli 1.75.0
```

**Comment by kamilogorek** [comment]
Is there any chance that you could provide more details about your setup/CI and all logs?
You can use `SENTRYCLI_SKIP_DOWNLOAD` to prevent fetching of the cli binary entirely and provide it yourself through cdn/gh releases as well. It all depends how your setup is working right now.

**Comment by marsh73** [comment]
not ignoring this... trying a different approach of not using the webpack plugin and attempting to create a run_binary target that will upload the sourcemaps outside of the webpack ecosystem.
