### ISSUE TITLE
`sourcemaps inject` prints error

### ISSUE THREAD

**Issue by AykutSarac** [getsentry/sentry-cli#1676]
### Environment

What version of the CLI and what OS are you running?
Version: 2.19.4
MacOS Ventura

### Steps to Reproduce

What you did?
- Run `sentry-cli sourcemaps inject`

### Expected/Actual Result

What you thought would happen and what actually happened?
- I'd expect a info message instead it printed the following:
```bash
thread 'unnamed' panicked at 'called `Option::unwrap()` on a `None` value': src/commands/sourcemaps/inject.rs:75

   0: backtrace::backtrace::trace

zsh: abort      sentry-cli sourcemaps inject
```

### Logs

```bash
  DEBUG   2023-07-10 11:33:21.261049 +03:00 sentry-cli version: 2.19.4, platform: "darwin", architecture: "arm64"
  INFO    2023-07-10 11:33:21.262027 +03:00 sentry-cli was invoked with the following command line: "sentry-cli" "sourcemaps" "inject" "--log-level=debug"
thread 'unnamed' panicked at 'called `Option::unwrap()` on a `None` value': src/commands/sourcemaps/inject.rs:75

   0: backtrace::backtrace::trace

zsh: abort      sentry-cli sourcemaps inject --log-level=debug
```

**Comment by kamilogorek** [comment]
Already fixed in https://github.com/getsentry/sentry-cli/pull/1662 Will be released soon.
For no, it just says that `sentry-cli sourcemaps inject` requires a path to be provided in the command itself.
