### ISSUE TITLE
Support preloaded modules in file RAM bundles

### ISSUE THREAD

**Issue by loewenheim** [getsentry/sentry-cli#1741]
By default, the index file of a file RAM bundle contains no code that should be hit during execution. All the action happens in the individual module files. Therefore, `sentry-cli` currently extracts the individual module sourcemaps from the bundle sourcemap, but doesn't take into account that the index file itself might also need a sourcemap.

However, if one enables module preloading as described in https://reactnative.dev/docs/ram-bundles-inline-requires#configure-preloading-and-inline-requires, not all modules reside in external files and we definitely need a sourcemap for the index file. We should figure out how to detect this case and how to extract the right individual sourcemap from the index sourcemap.

Fixes #1738.

**Comment by krystofwoldrich** [comment]
- Related issue from RN SDK https://github.com/getsentry/sentry-react-native/issues/2308

**Comment by krystofwoldrich** [comment]
### Minified stack trace in Sentry
```
Error: First error
  at onPress(app:///index.android.bundle:154:1938)
  at value(app:///239.js:1:8514)
  at value(app:///239.js:1:7770)
  at onResponderRelease(app:///239.js:1:5679)
  at o(app:///230.js:1:152)
  at h(app:///230.js:1:295)
  at g(app:///230.js:1:349)
  at S(app:///230.js:1:660)
  at Ne(app:///230.js:1:14306)
  at forEach([native code])
  at Y(app:///230.js:1:5327)
  at ? (app:///230.js:1:14655)
  at Pe(app:///230.js:1:98980)
  at Ce(app:///230.js:1:14116)
  at Le(app:///230.js:1:14493)
  at receiveTouches(app:///230.js:1:15281)
  at value(app:///index.android.bundle:28:3885)
  at ? (app:///index.android.bundle:28:762)
  at value(app:///index.android.bundle:28:2591)
  at value(app:///index.android.bundle:28:733)
  at value([native code])
```

### Minified stack trace converted for Metro Symbolicator
```
Error: First error
  at onPress@index.android.bundle:154:1938
  at value@239.js:1:8514
  at value@239.js:1:7770
  at onResponderRelease@239.js:1:5679
  at o@230.js:1:152
  at h@230.js:1:295
  at g@230.js:1:349
  at S@230.js:1:660
  at Ne@230.js:1:14306
  at forEach([native code])
  at Y@230.js:1:5327
  at ? @230.js:1:14655
  at Pe@230.js:1:98980
  at Ce@230.js:1:14116
  at Le@230.js:1:14493
  at receiveTouches@230.js:1:15281
  at value@index.android.bundle:28:3885
  at ? @index.android.bundle:28:762
  at value@index.android.bundle:28:2591
  at value@index.android.bundle:28:733
  at value([native code])
```

### Symbolicated stack trace in Sentry
```
Error: First error
  at <object>.{children#3}.onPress(App.tsx:88:65)
  at <object>.value(node_modules/react-native/Libraries/Pressability/Pressability.js:761:44)
  at <object>.responderEventHandlers(node_modules/react-native/Libraries/Pressability/Pressability.js:701:12)
  at n.onResponderRelease(node_modules/react-native/Libraries/Pressability/Pressability.js:530:7)
  at _dependencyMap(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:20:40)
  at h(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:37:56)
  at invokeGuardedCallbackImpl(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:43:3)
  at getFiberCurrentPropsFromNode(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:71:28)
  at Ne(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1119:44)
  at forEach([native code])
  at Y(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:360:38)
  at a(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1156:21)
  at Pe(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:8453:35)
  at Ce(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1103:29)
  at Le(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1135:14)
  at <object>.receiveTouches(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1207:22)
  at <object>.value(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:422:24)
  at <anonymous>(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:87:3)
  at <object>.moduleID(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:355:3)
  at <object>.value(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:84:12)
  at value([native code])
```

### Symbolicated stack trace in 
```
Error: First error
  at /Users/krystofwoldrich/random/ram-bundle-sentry-test/sentry-test/App.tsx:93:Button.props.onPress
  at /Users/krystofwoldrich/random/ram-bundle-sentry-test/sentry-test/node_modules/react-native/Libraries/Pressability/Pressability.js:762:_performTransitionSideEffects
  at /Users/krystofwoldrich/random/ram-bundle-sentry-test/sentry-test/node_modules/react-native/Libraries/Pressability/Pressability.js:701:_receiveSignal
  at /Users/krystofwoldrich/random/ram-bundle-sentry-test/sentry-test/node_modules/react-native/Libraries/Pressability/Pressability.js:530:responderEventHandlers.onResponderRelease
  at /Users/krystofwoldrich/random/ram-bundle-sentry-test/sentry-test/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:20:invokeGuardedCallbackImpl
  at /Users/krystofwoldrich/random/ram-bundle-sentry-test/sentry-test/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:37:invokeGuardedCallback
  at /Users/krystofwoldrich/random/ram-bundle-sentry-test/sentry-test/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:43:invokeGuardedCallbackAndCatchFirstError
  at /Users/krystofwoldrich/random/ram-bundle-sentry-test/sentry-test/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:71:executeDispatch
  at /Users/krystofwoldrich/random/ram-bundle-sentry-test/sentry-test/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1120:executeDispatchesAndReleaseTopLevel
  at forEach(null:null:null)
  at /Users/krystofwoldrich/random/ram-bundle-sentry-test/sentry-test/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:360:forEachAccumulated
  at ? @/Users/krystofwoldrich/random/ram-bundle-sentry-test/sentry-test/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1156:batchedUpdates$argument_0
  at /Users/krystofwoldrich/random/ram-bundle-sentry-test/sentry-test/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:8453:batchedUpdatesImpl
  at /Users/krystofwoldrich/random/ram-bundle-sentry-test/sentry-test/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1103:batchedUpdates
  at /Users/krystofwoldrich/random/ram-bundle-sentry-test/sentry-test/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1135:_receiveRootNodeIDEvent
  at /Users/krystofwoldrich/random/ram-bundle-sentry-test/sentry-test/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1207:ReactNativePrivateInterface.RCTEventEmitter.register$argument_0.receiveTouches
  at /Users/krystofwoldrich/random/ram-bundle-sentry-test/sentry-test/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:428:__callFunction
  at ? @/Users/krystofwoldrich/random/ram-bundle-sentry-test/sentry-test/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:113:__guard$argument_0
  at /Users/krystofwoldrich/random/ram-bundle-sentry-test/sentry-test/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:368:__guard
  at /Users/krystofwoldrich/random/ram-bundle-sentry-test/sentry-test/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:112:callFunctionReturnFlushedQueue
  at value(null:null:null)
```

### Note

```
# INCORRECT
Error: First error
  at <object>.{children#3}.onPress(App.tsx:88:65)
  
# CORRECT
Error: First error
  at /Users/krystofwoldrich/random/ram-bundle-sentry-test/sentry-test/App.tsx:93:Button.props.onPress
```
