### ISSUE TITLE
Cannot login using cli. Error `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by Grumaks** [getsentry/sentry-cli#1750]
### Environment

cli 2.20.7
macOS 13.4 (22F66)

### Steps to Reproduce

I use this on my ci:

`sentry-cli login --auth-token token_value `

### Expected/Actual Result

Actual: 
```
This helps you signing in your sentry-cli with an authentication token.
If you do not yet have a token ready we can bring up a browser for you
to create a token now.

Sentry server: sentry.io
thread 'unnamed' panicked at 'called `Option::unwrap()` on a `None` value': src/commands/login.rs:75


zsh: abort      sentry-cli login --auth-token 
```

Expected: 
Success login

### Logs
```
DEBUG   2023-09-21 17:47:00.960194 +02:00 sentry-cli version: 2.20.7, platform: "darwin", architecture: "arm64"
  INFO    2023-09-21 17:47:00.960364 +02:00 sentry-cli was invoked with the following command line: "sentry-cli" "login" "--auth-token" "token_value" "--log-level" "debug"
This helps you signing in your sentry-cli with an authentication token.
If you do not yet have a token ready we can bring up a browser for you
to create a token now.

Sentry server: sentry.io
  DEBUG   2023-09-21 17:47:00.961674 +02:00 request GET https://sentry.io/api/0/
  DEBUG   2023-09-21 17:47:00.961705 +02:00 using token authentication
  DEBUG   2023-09-21 17:47:00.962008 +02:00 retry number 0, max retries: 0
  DEBUG   2023-09-21 17:47:01.014202 +02:00 > GET /api/0/ HTTP/1.1
  DEBUG   2023-09-21 17:47:01.014220 +02:00 > Host: sentry.io
  DEBUG   2023-09-21 17:47:01.014223 +02:00 > Accept: */*
  DEBUG   2023-09-21 17:47:01.014226 +02:00 > Connection: TE
  DEBUG   2023-09-21 17:47:01.014228 +02:00 > TE: gzip
  DEBUG   2023-09-21 17:47:01.014231 +02:00 > User-Agent: sentry-cli/2.20.7
  DEBUG   2023-09-21 17:47:01.014469 +02:00 > Authorization: Bearer sntrys_e***
  DEBUG   2023-09-21 17:47:01.168354 +02:00 < HTTP/1.1 200 OK
  DEBUG   2023-09-21 17:47:01.168425 +02:00 < server: nginx
  DEBUG   2023-09-21 17:47:01.168443 +02:00 < date: Thu, 21 Sep 2023 15:47:01 GMT
  DEBUG   2023-09-21 17:47:01.168458 +02:00 < content-type: application/json
  DEBUG   2023-09-21 17:47:01.168472 +02:00 < Content-Length: 56
  DEBUG   2023-09-21 17:47:01.168492 +02:00 < allow: GET, HEAD, OPTIONS
  DEBUG   2023-09-21 17:47:01.168505 +02:00 < access-control-allow-methods: GET, HEAD, OPTIONS
  DEBUG   2023-09-21 17:47:01.168551 +02:00 < access-control-allow-headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding, sentry-trace, baggage, X-CSRFToken
  DEBUG   2023-09-21 17:47:01.168576 +02:00 < access-control-expose-headers: X-Sentry-Error, Retry-After
  DEBUG   2023-09-21 17:47:01.168623 +02:00 < access-control-allow-origin: *
  DEBUG   2023-09-21 17:47:01.168637 +02:00 < x-sentry-rate-limit-remaining: 39
  DEBUG   2023-09-21 17:47:01.168649 +02:00 < x-sentry-rate-limit-limit: 40
  DEBUG   2023-09-21 17:47:01.168661 +02:00 < x-sentry-rate-limit-reset: 1695311222
  DEBUG   2023-09-21 17:47:01.168672 +02:00 < x-sentry-rate-limit-concurrentremaining: 24
  DEBUG   2023-09-21 17:47:01.169375 +02:00 < x-sentry-rate-limit-concurrentlimit: 25
  DEBUG   2023-09-21 17:47:01.169391 +02:00 < vary: Accept-Language, Cookie
  DEBUG   2023-09-21 17:47:01.169403 +02:00 < content-language: en
  DEBUG   2023-09-21 17:47:01.169417 +02:00 < x-frame-options: deny
  DEBUG   2023-09-21 17:47:01.169428 +02:00 < x-content-type-options: nosniff
  DEBUG   2023-09-21 17:47:01.169440 +02:00 < x-xss-protection: 1; mode=block
  DEBUG   2023-09-21 17:47:01.169459 +02:00 < content-security-policy: frame-ancestors 'self' *.sentry.io; img-src * blob: data:; script-src 'self' 'unsafe-inline' 'report-sample' 'unsafe-eval' s1.sentry-cdn.com js.sentry-cdn.com browser.sentry-cdn.com statuspage-production.s3.amazonaws.com static.zdassets.com aui-cdn.atlassian.com connect-cdn.atl-paas.net js.stripe.com ssl.google-analytics.com 'strict-dynamic' cdn.pendo.io data.pendo.io pendo-io-static.storage.googleapis.com pendo-static-5634074999128064.storage.googleapis.com; object-src 'self'; default-src *; base-uri 'none'; style-src * 'unsafe-inline'; connect-src *; font-src * data:; report-uri https://o1.ingest.sentry.io/api/54785/security/?sentry_key=f724a8a027db45f5b21507e7142ff78e&sentry_release=0dddb7dff5ebb67f15c00f89ff48f3334430c580
  DEBUG   2023-09-21 17:47:01.170202 +02:00 < x-envoy-attempt-count: 1
  DEBUG   2023-09-21 17:47:01.170217 +02:00 < x-envoy-upstream-service-time: 31
  DEBUG   2023-09-21 17:47:01.170229 +02:00 < x-served-by: getsentry-web-default-common-production-7b765d8979-zxcf6
  DEBUG   2023-09-21 17:47:01.170241 +02:00 < x-served-by: frontend-default-5494b6bc88-k67rn
  DEBUG   2023-09-21 17:47:01.170254 +02:00 < strict-transport-security: max-age=31536000; includeSubDomains; preload
  DEBUG   2023-09-21 17:47:01.171147 +02:00 < via: 1.1 google
  DEBUG   2023-09-21 17:47:01.171161 +02:00 < Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
  DEBUG   2023-09-21 17:47:01.171229 +02:00 response status: 200
  DEBUG   2023-09-21 17:47:01.171413 +02:00 body: {"version":"0","auth":{"scopes":["org:ci"]},"user":null}
thread 'unnamed' panicked at 'called `Option::unwrap()` on a `None` value': src/commands/login.rs:75


zsh: abort      sudo sentry-cli login --auth-token  --log-level debug
```

*I use my organisation token. With my personal token I can successfully login.*

**Comment by loewenheim** [comment]
Hi, thank you for the report.

**Comment by loewenheim** [comment]
This is fixed in 2.21.0.

**Comment by itx-benjamin-jasper** [comment]
Hi,

it seems like this issue may not have been fixed yet. I'm having similar problems (version 2.21.0), same conditions using an organization auth token returns the following error, a user auth token works.

```
sentry-cli login --auth-token sntrys_<my token>

error: Failed to parse org auth token {token}
  caused by: invalid type: null, expected a string at line 1 column 35
```

**Comment by loewenheim** [comment]
Hi, can you decode the part between the two underscores with e.g. https://www.base64decode.org/ and tell me what it contains? You don't need to post the actual contents of the fields, only which fields exist and whether they're null.

**Comment by loewenheim** [comment]
Yeah `"url"` being null is not good. Are you using Sentry SaaS?

**Comment by itx-benjamin-jasper** [comment]
I figured as much 🙃 we are using a self hosted instance. Is this generally an problem or should this be moved to the self hosted repo?

**Comment by itx-benjamin-jasper** [comment]
Turns out we should have read the manual better, apparently we were missing the `system.url-prefix` line in the sentry/config.yml. Interestingly the `region_url` field was very much correct.

Thank you so much for pointing us in the right direction! ❤️

**Comment by Grumaks** [comment]
```
Sentry server: sentry.io
Valid org token
```

works for me, thx!

**Comment by hubertdeng123** [comment]
Hi there, @itx-benjamin-jasper. For the docker compose version of self-hosted Sentry, the `system.url-prefix` is prompted for during the initial setup screen. Could you give me context on why that option was not set?

**Comment by itx-benjamin-jasper** [comment]
Hi @hubertdeng123,
we probably hit some weird edge case, where we reinstalled sentry after pruning all volumes (we had a broken installation, because we were initially using a nightly build by accident).
I think, that these weird circumstances may have resulted in us not deleting something else we should have, before reinstaling... Normal users hopefully never encounter this.
Sorry I can't tell you antyhing more specific

**Comment by hubertdeng123** [comment]
Got it, thanks for letting me know.
