### ISSUE TITLE
Sentrycli upload sourcemaps failed when log level set to info

### ISSUE THREAD

**Issue by chenliangyu** [getsentry/sentry-cli#206]
I'm install the latest version(1.27.1) of SentryCli via NPM, and I've created a gulp task to use SentryCli to create release and upload files.

.sentryclirc
```
[log]
level=info
```

The Gulp Task copied code from @sentry/webpack-plugin
```
gulp.task('sentry_release', ['setEnvVariable'], () => {
    const options = {
      rewrite: true,
      include: ['./dest/scripts'],
      urlPrefix: 'static/js',
      validate: true,
    };
    const release = process.env.sentryRelease;
    const sentryCli = new SentryCli();
    return sentryCli
      .createRelease(release)
      .then(() => {
        return sentryCli.uploadSourceMaps(options);
      })
      .then(() => {
        return sentryCli.finalizeRelease(release);
      });
  });
```

Running Result:
```
[19:15:36] Starting 'sentry_release'...
Created release [ONLINE]:test.

[19:15:39] 'sentry_release' errored after 3.23 s
[19:15:39] Error: stderr maxBuffer exceeded
    at Socket.onChildStderr (child_process.js:343:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:249:13)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at Pipe.onread (net.js:587:20)
```

There is 25 files in dest/scripts, include minified js file and map file, the size is about 38 MB.

When I change the log level to warning, it works

and I found the node version of SentryCli is using `execFile` to run command, MaxBuffer for `execFile` is set to 200*1024 bytes, or ~204.8KB，I think maybe the node version of SentryCli can add an option to increase MaxBuffer.

**Comment by etagwerker** [comment]
I'm getting a similar issue, but changing log level to warning is not solving this for me. 

Unfortunately there isn't much of a backtrace from my app:

```
NODE_PATH=/Users/etagwerker/Projects/ombulabs/project_1/node_modules /Users/etagwerker/Projects/ombulabs/project_1/node_modules/.bin/webpack --config /Users/etagwerker/Projects/ombulabs/project_1/config/webpack/production.js
(node:20829) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Hash: 307456f1f33b3251ff70
Version: webpack 2.7.0
Time: 51447ms
                                     Asset       Size  Chunks                    Chunk Names
administrator-307456f1f33b3251ff70.css.map  115 bytes       1  [emitted]         administrator
           teacher-c6b56962674f35bbc335.js    1.47 MB       0  [emitted]  [big]  teacher
           student-fae5861f7d3c0db44b7a.js     623 kB       2  [emitted]  [big]  student
       application-dfd36c0188a02fd89898.js  957 bytes       3  [emitted]         application
    administrator-307456f1f33b3251ff70.css    12.2 kB       1  [emitted]         administrator
          teacher-307456f1f33b3251ff70.css    22.1 kB       0  [emitted]         teacher
       teacher-c6b56962674f35bbc335.js.map    10.8 MB       0  [emitted]         teacher
      teacher-307456f1f33b3251ff70.css.map  109 bytes       0  [emitted]         teacher
 administrator-b10b7b5149405559b7f0.js.map    9.56 MB       1  [emitted]         administrator
     administrator-b10b7b5149405559b7f0.js    1.28 MB       1  [emitted]  [big]  administrator
       student-fae5861f7d3c0db44b7a.js.map    6.22 MB       2  [emitted]         student
   application-dfd36c0188a02fd89898.js.map    9.98 kB       3  [emitted]         application
    application-dfd36c0188a02fd89898.js.gz  550 bytes          [emitted]
 administrator-307456f1f33b3251ff70.css.gz    1.97 kB          [emitted]
       teacher-307456f1f33b3251ff70.css.gz    3.73 kB          [emitted]
        student-fae5861f7d3c0db44b7a.js.gz     177 kB          [emitted]
  administrator-b10b7b5149405559b7f0.js.gz     338 kB          [emitted]  [big]
        teacher-c6b56962674f35bbc335.js.gz     385 kB          [emitted]  [big]
                             manifest.json  818 bytes          [emitted]
   [0] ./~/react/react.js 56 bytes {0} {1} {2} [built]
  [35] ./~/react-dom/index.js 59 bytes {0} {1} {2} [built]
  [68] (webpack)/buildin/global.js 509 bytes {0} {1} {2} {3} [built]
 [247] ./~/@sentry/webpack-plugin/src/sentry-webpack.module.js 94 bytes {0} {1} {2} {3} [built]
 [421] ./~/babel-polyfill/lib/index.js 833 bytes {0} {1} {2} [built]
 [941] ./~/react-dom/lib/ReactDOM.js 5.05 kB {0} {1} {2} [built]
[1247] ./app/javascript/packs/application.js 515 bytes {3} [built]
[1248] ./app/javascript/packs/administrator.jsx 429 bytes {1} [built]
[1249] ./app/javascript/packs/student.jsx 1.3 kB {2} [built]
[1250] ./app/javascript/packs/teacher.jsx 606 bytes {0} [built]
[1295] ./~/redux-saga/es/index.js 497 bytes {0} [built]
[1302] multi ./~/@sentry/webpack-plugin/src/sentry-webpack.module.js ./app/javascript/packs/administrator.jsx 40 bytes {1} [built]
[1303] multi ./~/@sentry/webpack-plugin/src/sentry-webpack.module.js ./app/javascript/packs/application.js 40 bytes {3} [built]
[1304] multi ./~/@sentry/webpack-plugin/src/sentry-webpack.module.js ./app/javascript/packs/student.jsx 40 bytes {2} [built]
[1305] multi ./~/@sentry/webpack-plugin/src/sentry-webpack.module.js ./app/javascript/packs/teacher.jsx 40 bytes {0} [built]
    + 1296 hidden modules

ERROR in Sentry CLI Plugin: stderr maxBuffer exceeded
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 2.26 kB {0} [built]
       [1] ./~/css-loader!./~/postcss-loader!./~/sass-loader/lib/loader.js!./~/react-datepicker/dist/react-datepicker.css 12.7 kB {0} [built]
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 2.26 kB {0} [built]
       [1] ./~/css-loader!./~/postcss-loader!./~/sass-loader/lib/loader.js!./~/react-select/dist/react-select.css 10.3 kB {0} [built]
```

**Comment by bijeebuss** [comment]
This happens to me when I use inline-source-map but not when I use source-map
