### ISSUE TITLE
getPath error in CLI 1.28.0 (NPM package `@sentry/cli@1.28.0`)

### ISSUE THREAD

**Issue by EirikBirkeland** [getsentry/sentry-cli#210]
```javascript
var child = require('child_process').spawn(cli.getPath(), process.argv.slice(2), {
                                               ^
TypeError: cli.getPath is not a function
    at Object.<anonymous> (/home/eb/.npm-global/lib/node_modules/@sentry/cli/bin/sentry-cli:6:48)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Could it be that `js/index.js` is missing `getPath` method?

``` javascript
'use strict';

var pkgInfo = require('../package.json');
var helper = require('./helper');

function SentryCli(configFile) {
  if (typeof configFile === 'string') process.env.SENTRY_PROPERTIES = configFile;
}
SentryCli.prototype.getConfigStatus = function() {
  return helper.execute(['info', '--config-status-json']);
};
SentryCli.getVersion = function() {
  return pkgInfo.version;
};

SentryCli.prototype.releases = require('./releases');

module.exports = SentryCli;
```

**Comment by EirikBirkeland** [comment]
I will use previous version for now. Thanks!

**Comment by HazAT** [comment]
@EirikBirkeland Fix is on the way!
