### ISSUE TITLE
Broken cli npm package since 1.28.0

### ISSUE THREAD

**Issue by samosad** [getsentry/sentry-cli#212]
One of my build steps is uploading source maps to sentry with @sentry/cli npm tool,
here it is:
```
    - yarn add @sentry/cli
    - |
      ./node_modules/.bin/sentry-cli \
        --api-key $SENTRY_API_KEY> \
        --url $SENTRY_HOST \
        releases --org $SENTRY_ORG --project $SENTRY_PROJECT \
        files $CI_BUILD_REF_NAME \
        upload-sourcemaps --validate public/assets
```

it worked well before today;
since latest release came there is an error in console:
```
/home/gitlab-runner/builds_0/39c0a24a/0/web/node_modules/@sentry/cli/bin/sentry-cli:6
var child = require('child_process').spawn(cli.getPath(), process.argv.slice(2), {
                                               ^

TypeError: cli.getPath is not a function
    at Object.<anonymous> (/home/gitlab-runner/builds_0/39c0a24a/0/web/node_modules/@sentry/cli/bin/sentry-cli:6:48)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

when i switch back to @sentry/cli@1.27.1 everything works well again:
```
> Analyzing 6 sources
> ~/app.js
> Adding source map references
> Validating sources
> ~/vendor.js.map
> Uploading source maps for release 5.1.4

sentry-cli update to 1.28.0 is available!
run sentry-cli update to update
```

**Comment by EirikBirkeland** [comment]
Dupe of #210

I also am using `@1.27.1` for the time being

**Comment by samosad** [comment]
thanks @EirikBirkeland !
