### ISSUE TITLE
Panic with `--auth-token` argument

### ISSUE THREAD

**Issue by szokeasaurusrex** [getsentry/sentry-cli#2170]
### CLI Version

2.36.2 (master)

### Operating System and Architecture

- [x] macOS (arm64)
- [ ] macOS (x86_64)
- [ ] Linux (i686)
- [ ] Linux (x86_64)
- [ ] Linux (armv7)
- [ ] Linux (aarch64)
- [ ] Windows (i686)
- [ ] Windows (x86_64)

### Operating System Version

macOS 14.4.1

### CLI Command

sentry-cli monitors run --auth-token=asdf asdf -- echo hi

### Exact Reproduction Steps

Run `sentry-cli monitors run` with an `--auth-token` argument.

### Expected Results

No panic, the command is run.

### Actual Results

Sentry CLI panics

### Logs

```
thread 'main' panicked at 'Mismatch between definition and access of `auth_token`. Could not downcast to sentry_cli::utils::auth_token::auth_token_impl::AuthToken, need to downcast to alloc::string::String
': src/commands/mod.rs:117

   0: backtrace::backtrace::libunwind::trace
             at /Users/dszoke/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.73/src/backtrace/libunwind.rs:116:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/dszoke/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.73/src/backtrace/mod.rs:66:5
   1: backtrace::backtrace::trace
             at /Users/dszoke/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.73/src/backtrace/mod.rs:53:14
   2: backtrace::capture::Backtrace::create
             at /Users/dszoke/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.73/src/capture.rs:197:9
   3: backtrace::capture::Backtrace::new
             at /Users/dszoke/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.73/src/capture.rs:162:22
   4: sentry_cli::utils::system::init_backtrace::{{closure}}
             at /Users/dszoke/Development/sentry-cli/src/utils/system.rs:99:25
   5: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/boxed.rs:2084:9
      std::panicking::rust_panic_with_hook
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:808:13
   6: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:674:13
   7: std::sys::backtrace::__rust_end_short_backtrace
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:168:18
   8: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   9: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
  10: clap_builder::parser::error::MatchesError::unwrap
             at /Users/dszoke/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.5.8/src/parser/error.rs:32:9
  11: clap_builder::parser::matches::arg_matches::ArgMatches::get_one
             at /Users/dszoke/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.5.8/src/parser/matches/arg_matches.rs:115:9
  12: sentry_cli::commands::configure_args
             at /Users/dszoke/Development/sentry-cli/src/commands/mod.rs:117:31
  13: sentry_cli::commands::execute
             at /Users/dszoke/Development/sentry-cli/src/commands/mod.rs:262:5
  14: sentry_cli::commands::main
             at /Users/dszoke/Development/sentry-cli/src/commands/mod.rs:355:27
  15: sentry_cli::main
             at /Users/dszoke/Development/sentry-cli/src/main.rs:8:5
  16: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
  17: std::sys::backtrace::__rust_begin_short_backtrace
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:152:18
  18: std::rt::lang_start::{{closure}}
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:162:18
  19: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
      std::panicking::try
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
      std::panic::catch_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:141:48
      std::panicking::try::do_call
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
      std::panicking::try
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
      std::panic::catch_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
      std::rt::lang_start_internal
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:141:20
  20: std::rt::lang_start
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:161:17
  21: _main
```

**Comment by szokeasaurusrex** [comment]
`--auth-token` argument not needed for `monitors run` since we use DSN auth, but we should check whether other commands could be affected.
