### ISSUE TITLE
Install: support android platform

### ISSUE THREAD

**Issue by cbix** [getsentry/sentry-cli#2288]
Just tried `npm install` from [termux](https://termux.dev/en/) where node's `os.platform()` returns `android`. It failed in sentry's postinstall step due to the platform not being supported.

The linux binary should work out of the box since it's statically linked.

**Comment by szokeasaurusrex** [comment]
@cbix thanks for opening this issue. Do any of the [other install methods](https://docs.sentry.io/cli/installation/) work for you on Android?

**Comment by cbix** [comment]
Manual install works, but inside my package `npm install` still fails because it has `@sentry/cli` as dependency where the postinstall script fails.

**Comment by szokeasaurusrex** [comment]
@cbix got it, thanks

**Comment by szokeasaurusrex** [comment]
@leaftail1880 Thank you for letting us know.

**Comment by aldoetobex** [comment]
> Really need this feature. Sometimes i need to check app code on the phone and this is a blocker for me because it breaks install of other platform-aware dependencies (and they all support android!)

I totally agree! This package is currently the only blocker for me when trying to install platform-aware dependencies. I often need to check app code directly on my phone, but the post-install error with @sentry/cli makes it quite challenging. It would be great if this could be resolved, as other similar packages already support Android.

Thanks in advance to the maintainers for looking into this. I really appreciate your hard work! 🙏

```
npm error code 1
npm error path /root/xxx/node_modules/@sentry/cli
npm error command failed
npm error command sh -c node ./scripts/install.js
npm error /root/xxx/node_modules/@sentry/cli/js/helper.js:98
npm error   throw new Error(
npm error   ^
npm error
npm error Error: Unsupported operating system or architecture! Sentry CLI does not work on this architecture.
npm error
npm error Sentry CLI supports:
npm error - Darwin (macOS)
npm error - Linux and FreeBSD on x64, x86, ia32, arm64, and arm architectures
npm error - Windows x64, x86, and ia32 architectures
npm error     at Object.throwUnsupportedPlatformError (/root/xxx/node_modules/@sentry/cli/js/helper.js:98:9)
npm error     at Object.<anonymous> (/root/xxx/node_modules/@sentry/cli/scripts/install.js:320:10)
npm error     at Module._compile (node:internal/modules/cjs/loader:1730:14)
npm error     at Module._extensions..js (node:internal/modules/cjs/loader:1895:10)
npm error     at Module.load (node:internal/modules/cjs/loader:1465:32)
npm error     at Module._load (node:internal/modules/cjs/loader:1282:12)
npm error     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
npm error     at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
npm error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
npm error     at node:internal/main/run_main_module:36:49
npm error
npm error Node.js v22.15.0
npm error A complete log of this run can be found in: /root/.npm/_logs/2025-05-12T08_53_22_495Z-debug-0.log
```

**Comment by szokeasaurusrex** [comment]
Hey, thanks guys for reaching out. I am gonna bump the priority of this issue on our backlog, but since we have a bunch of other priorities, it could take some time.<br><br>PRs are always welcome, though, if someone would like to contribute!

**Comment by szokeasaurusrex** [comment]
Hey, we are adding this feature in version 2.46.0 of Sentry CLI, which will be released shortly

**Comment by aldoetobex** [comment]
> Hey, we are adding this feature in version 2.46.0 of Sentry CLI, which will be released shortly

Thank you! I’m glad to hear about this update, I really appreciate it. I’ll let you know if I encounter any other issues with version 2.46.0 once it’s released.
