### ISSUE TITLE
Installation fails due to TypeError

### ISSUE THREAD

**Issue by selfagency** [getsentry/sentry-cli#286]
i'm on mac os 10.13.4 and my node version is 9.11.1.

```
❯ yarn global add sentry-cli
yarn global v1.6.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/1] ⠐ sentry-cli:     at FSReqWrap.oncomplete (fs.js:153:20)
[-/1] ⠐ waiting...
[-/1] ⠐ waiting...
[-/1] ⠐ waiting...
error /Users/daniel/.config/yarn/global/node_modules/sentry-cli: Command failed.
Exit code: 1
Command: node tasks/download.js
Arguments:
Directory: /Users/daniel/.config/yarn/global/node_modules/sentry-cli
Output:
path.js:39
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.join (path.js:1158:7)
```

**Comment by jan-auer** [comment]
You are trying to install the wrong package, please install `@sentry/cli` instead:

```
$ yarn global add @sentry/cli
yarn global v1.6.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed "@sentry/cli@1.30.5" with binaries:
      - sentry-cli
✨  Done in 2.38s.
```
