### ISSUE TITLE
Unable to upload debug info

### ISSUE THREAD

**Issue by BlackHole1** [getsentry/sentry-cli#345]
my sentry.properties:
```javascript
defaults.url=https://sentry.hibot.net/
defaults.org=alo7
defaults.project=aoc-desktop-crash-in
auth.token=acb488aa··········
```

`sentry-cli info`:
```javascript
Sentry Server: https://sentry.hibot.net/
Default Organization: alo7
Default Project: aoc-desktop-crash-in

Authentication Info:
  Method: Auth Token
  User: black-hole@alo7.com
  Scopes:
    - event:admin
    - member:read
    - org:read
    - project:read
    - project:releases
    - team:read
    - project:write
    - team:write
    - member:admin
    - org:write
    - team:admin
    - project:admin
    - org:admin
    - event:read
```

But you can't upload debug info.

`sentry-cli upload-dif -t dsym alo7-portal.node.dSYM`:
```
> Found 1 debug information file
> Prepared debug information file for upload
> Nothing to upload, all files are on the server
```

He says the server has already existed, But I didn't see it in my project.

![image](https://user-images.githubusercontent.com/8198408/43073291-97e4cee0-8eab-11e8-87ee-3ecc594a6636.png)

very strange. The crash log can be captured:

![image](https://user-images.githubusercontent.com/8198408/43073343-cce984b4-8eab-11e8-8dc2-2411e277472a.png)

### Let me explain what I did:

1. There was no problem before.
2. At the last time of uploading
3. When processing files, I used `ctrl+c`
4. And then it can't be uploaded

How should I delete the files on the server or delete the local cache files?
Can sentry-cli be forced to upload?

**Comment by BlackHole1** [comment]
The problem is due to my ctrl+c. I'm sorry. But I don't know how to solve it. I've tried a lot of methods that don't work. Sorry to trouble you.

**Comment by BlackHole1** [comment]
I think it's my local problem, because I modified sentry's URL, org, project and auth.token. Still can't upload. I don't know how to solve it. This is just my guess

**Comment by BlackHole1** [comment]
OK, thank you very much for your reply. I don't know what I should do and help you.

Do you need me to provide sentry server logs?

**Comment by jan-auer** [comment]
Thanks for offering help. Right now I don't need you to do anything.
Please only check that you're able to upload debug information files without pressing CTRL+C so that they appear in your project.

**Comment by BlackHole1** [comment]
I tried not to press `Ctrl + c`, but show `Nothing to upload, all files are on the server`

I tried to modify the `sentry.properties` file, The output is also `Nothing to upload, all files are on the server`

I don't know whether it's my local problem or the remote server's problem. Because since I modified the `sentry.properties` file, I uploaded it should be no problem. But his display is always  `Nothing to upload, all files are on the server`

**Comment by jan-auer** [comment]
You need to upload new symbols.

**Comment by BlackHole1** [comment]
I tried, but the result was the same

**Comment by BlackHole1** [comment]
I just rechecked it. I found that after I modified `sentry.properties`, I can upload it. I'm sorry to have brought you misleading information before.

Let me reexplain the question:
When I use the new symbols, the result of `sentry server` is always `Nothing to upload, all files are on the server`.

It seems to be judging some problems and letting the result is always true

**Comment by BlackHole1** [comment]
When I restarted the computer and uploaded it again, the following error occurred:
```
Command failed: /Users/black-hole/Code/Job/aoc/packages/alo7-portal/node_modules/.bin/sentry-cli upload-dif -t dsym /Users/black-hole/Code/Job/aoc/packages/alo7-portal/lib/symbol/mac/x64/alo7-portal.node.dSYM
error: not a JSON response

    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:595:12)
```

**Comment by eyuxin** [comment]
@BlackHole1  I have the same issue, how can I configure the SENTRY_FILESTORE_DIR?

**Comment by kamilogorek** [comment]
Its env variable in your docker image. See https://github.com/getsentry/onpremise/issues/203#issuecomment-474343800 for an example
