### ISSUE TITLE
error in post symbol file

### ISSUE THREAD

**Issue by BlackHole1** [getsentry/sentry-cli#352]
output:
```shell
> cross-env SENTRY_PROPERTIES=./sentry.properties PLATFORM=mac ARCH=x64 node ./script/post-addon-sym.js

success post symbol file to sentry. output:
> Found 1 debug information file
> Prepared debug information file for upload
> Uploaded 1 missing debug information file
> File processing complete:

     OK 0c3a1921-ba6c-350d-b240-0003af6d693f (VideoSource; x86_64)
> skipped reprocessing

error post symbol file to sentry. output:
{ Error: Command failed: /Users/saybot/builds/b82cb74c/0/kejian/aoc/packages/agora-rtc-for-electron/node_modules/.bin/sentry-cli upload-dif --no-reprocessing -t dsym /Users/saybot/builds/b82cb74c/0/kejian/aoc/packages/agora-rtc-for-electron/lib/symbol/mac/x64/agora_node_ext.node.dSYM
[WARN] goblin::mach::segment section #1 size 10230064 out of bounds
error: not a JSON response

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/saybot/builds/b82cb74c/0/kejian/aoc/packages/agora-rtc-for-electron/node_modules/.bin/sentry-cli upload-dif --no-reprocessing -t dsym /Users/saybot/builds/b82cb74c/0/kejian/aoc/packages/agora-rtc-for-electron/lib/symbol/mac/x64/agora_node_ext.node.dSYM' }
```

The first file is no problem, but the second file failed to upload.

**Comment by BlackHole1** [comment]
what is `[WARN] goblin::mach::segment section #1 size 10230064 out of bounds`？

**Comment by BlackHole1** [comment]
Is the file too large to allow the server to not allow uploads

**Comment by jan-auer** [comment]
Sorry for not being able to investigate this issue last week. May I ask how you resolved your issue?

**Comment by BlackHole1** [comment]
@jan-auer 
Solution: repack a symbols file and upload it.

But this will happen occasionally. The specific reason is not clear to us.
