### ISSUE TITLE
set-commits --auto fails with thread 'unnamed' panicked at 'called `Option::unwrap()` on a `None` value': libcore/option.rs:345

### ISSUE THREAD

**Issue by mkj28** [getsentry/sentry-cli#361]
$ sentry-cli releases --org myorg --project myproject set-commits --auto deadbeef
```
thread 'unnamed' panicked at 'called `Option::unwrap()` on a `None` value': libcore/option.rs:345

stack backtrace:
   0:        0x10d48e8fe - backtrace::backtrace::trace::h514d75a2770f3a20
   1:        0x10d48dabc - <backtrace::capture::Backtrace as core::default::Default>::default::hd67a7078af019b2d
   2:        0x10d48db3d - backtrace::capture::Backtrace::new::h5baec8c77729d101
   3:        0x10cf6ee71 - sentry_cli::utils::system::init_backtrace::{{closure}}::h26ca47531760abc3
   4:        0x10d53f11e - std::panicking::rust_panic_with_hook::h81c4f3add25e6667
   5:        0x10d53ee9e - std::panicking::continue_panic_fmt::hfa057b7c1de88179
   6:        0x10d53eb28 - _rust_begin_unwind
   7:        0x10d582b01 - core::panicking::panic_fmt::h4c82aa4e615d52a2
   8:        0x10d582a36 - core::panicking::panic::h8d7a5d68453b6367
   9:        0x10d244282 - git2::submodule::Submodule::url::ha15141ec10c35408
  10:        0x10cee84cb - sentry_cli::utils::vcs::find_matching_rev::h5a7f7ceee132c9d2
  11:        0x10ceea89a - sentry_cli::utils::vcs::find_heads::h5b1a7d6c11fb2662
  12:        0x10cf3b393 - sentry_cli::commands::releases::execute::h31840f3dcc5fdd5b
  13:        0x10cfb72e2 - sentry_cli::commands::execute::h5c86ca1bc5561683
  14:        0x10cfba28f - sentry_cli::commands::main::h66560463e3fc4490
  15:        0x10cea5a5e - std::sys_common::backtrace::__rust_begin_short_backtrace::he078224dc1906de5
  16:        0x10d54b2de - ___rust_maybe_catch_panic
  17:        0x10cead189 - <F as alloc::boxed::FnBox<A>>::call_box::h8591435a0ab88a95
  18:        0x10d53df77 - std::sys_common::thread::start_thread::h78b1dd404be976ad
  19:        0x10d5210d8 - std::sys::unix::thread::Thread::new::thread_start::h27c6becca8cf44e0
  20:     0x7fff674a4660 - __pthread_body
  21:     0x7fff674a450c - __pthread_start
```

$ git log deadbeef
```
commit deadbeef
Author: Jane Developer <jane@myorg.com>
Date:   Thu Aug 23 11:03:42 2018 -0700
```

At the same time this works:
`sentry-cli releases --org myorg --project myproject set-commits deadbeef --commit "myorg/myrepo@deadbeef"`

What am I doing wrong?

**Comment by mkj28** [comment]
--auto works after removal

**Comment by mitsuhiko** [comment]
Going to keep this open until we upgrade libgit2 which fixes the panic.
