### ISSUE TITLE
SEC_E_BUFFER_TOO_SMALL

### ISSUE THREAD

**Issue by secit-pl** [getsentry/sentry-cli#380]
While building cordova application on Windows 7 we have following error (on Mac all is ok): 

```
Uploading assets release: 'bb7aed22df47a0684efd' path: C:\app\platforms\android\app\src\main\assets\www
(node:14964) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command failed: C:\app\node_modules\@sentry\cli\bin\sentry
-cli.exe releases finalize bb7aed22df47a0684efd
error: API request failed
  caused by: [35] SSL connect error (schannel: next InitializeSecurityContext failed: SEC_E_BUFFER_TOO_SMALL (0x80090321) - Bufor udostępniony funkcji jest za mały.)
```

After upgrading node to 10.0.10 we have different error:

```
Uploading assets release: 'bb7aed22df47a0684efd' path: C:\app\platforms\android\app\src\main\assets\www
(node:13172) UnhandledPromiseRejectionWarning: Error: Command failed: C:\app\node_modules\@sentry\cli\bin\sentry-cli.exe releases files bb7aed22df47a0684efd upload-sourcemaps C:\app\platforms\android\app\src\main\as
sets\www/plugins/cordova-plugin-geolocation/www/android/geolocation.js --ignore node_modules
error: API request failed
  caused by: [35] SSL connect error (schannel: next InitializeSecurityContext failed: SEC_E_MESSAGE_ALTERED (0x8009030F) - Komunikat lub podpis przedłożony do weryfikacji został  zmieniony.)

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
(node:13172) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13172) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kemsky** [comment]
@jan-auer, is there any work around?

**Comment by kamilogorek** [comment]
curl is now statically linked and this issue should be resolved. Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
