### ISSUE TITLE
Heroku deploy: error: Could not automatically determine release name

### ISSUE THREAD

**Issue by shackra** [getsentry/sentry-cli#536]
So, I have Sentry installed on my heroku dyno.

I use dpl in Gitlab for the release with the Git strategy, however the deploy fails because of Sentry and honestly I cannot figure out what wrong.

did ran `heroku labs:enable runtime-dyno-metadata` but the result was the same.

```
Running with gitlab-runner 11.10.1 (1f513601)
  on docker-auto-scale 0277ea0f
Using Docker executor with image node:11.15.0-stretch-slim ...
Pulling docker image node:11.15.0-stretch-slim ...
Using docker image sha256:714efe4cc015aa709e99c0ae270253a88341078c15dc830fc9e376b2f4e894fc for node:11.15.0-stretch-slim ...
Running on runner-0277ea0f-project-12525873-concurrent-0 via runner-0277ea0f-srm-1558856404-f2a13d6f...
Initialized empty Git repository in /builds/kuecr/fero/frontend/.git/
Fetching changes...
Created fresh repository.
From https://gitlab.com/kuecr/fero/frontend
 * [new branch]      dev        -> origin/dev
 * [new tag]         0.1.0      -> 0.1.0
Checking out e25dcbe2 as dev...

Skipping Git submodules setup
$ apt-get update -yq && apt-get install -y ruby-dev git
Ign:1 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:2 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2434 B]
Get:4 http://security-cdn.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages [27.2 kB]
Get:7 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [7082 kB]
Get:8 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages [492 kB]
Fetched 7907 kB in 1s (4440 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  fonts-lato git-man javascript-common less libbsd0 libcurl3-gnutls libedit2
  liberror-perl libexpat1 libgdbm3 libgmp-dev libgmpxx4ldbl libgpm2
  libjs-jquery libncurses5 libperl5.24 libpopt0 libruby2.3 libx11-6
  libx11-data libxau6 libxcb1 libxdmcp6 libxext6 libxmuu1 libyaml-0-2 netbase
  openssh-client patch perl perl-modules-5.24 rake rename rsync ruby
  ruby-did-you-mean ruby-minitest ruby-net-telnet ruby-power-assert
  ruby-test-unit ruby2.3 ruby2.3-dev rubygems-integration unzip xauth zip
Suggested packages:
  gettext-base git-daemon-run | git-daemon-sysvinit git-doc git-el git-email
  git-gui gitk gitweb git-arch git-cvs git-mediawiki git-svn apache2
  | lighttpd | httpd gmp-doc libgmp10-doc libmpfr-dev gpm keychain libpam-ssh
  monkeysphere ssh-askpass ed diffutils-doc perl-doc libterm-readline-gnu-perl
  | libterm-readline-perl-perl make openssh-server ri bundler
The following NEW packages will be installed:
  fonts-lato git git-man javascript-common less libbsd0 libcurl3-gnutls
  libedit2 liberror-perl libexpat1 libgdbm3 libgmp-dev libgmpxx4ldbl libgpm2
  libjs-jquery libncurses5 libperl5.24 libpopt0 libruby2.3 libx11-6
  libx11-data libxau6 libxcb1 libxdmcp6 libxext6 libxmuu1 libyaml-0-2 netbase
  openssh-client patch perl perl-modules-5.24 rake rename rsync ruby ruby-dev
  ruby-did-you-mean ruby-minitest ruby-net-telnet ruby-power-assert
  ruby-test-unit ruby2.3 ruby2.3-dev rubygems-integration unzip xauth zip
0 upgraded, 48 newly installed, 0 to remove and 0 not upgraded.
Need to get 24.2 MB of archives.
After this operation, 119 MB of additional disk space will be used.
Get:1 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 perl-modules-5.24 all 5.24.1-3+deb9u5 [2722 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libgdbm3 amd64 1.8.3-14 [30.0 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libperl5.24 amd64 5.24.1-3+deb9u5 [3501 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 perl amd64 5.24.1-3+deb9u5 [219 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 fonts-lato all 2.0-1 [2684 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libcurl3-gnutls amd64 7.52.1-5+deb9u9 [290 kB]
Get:7 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libexpat1 amd64 2.2.0-2+deb9u1 [83.4 kB]
Get:8 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 liberror-perl all 0.17024-1 [26.9 kB]
Get:9 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 git-man all 1:2.11.0-3+deb9u4 [1433 kB]
Get:10 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 git amd64 1:2.11.0-3+deb9u4 [4167 kB]
Get:11 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libxau6 amd64 1:1.0.8-1 [20.7 kB]
Get:12 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libpopt0 amd64 1.16-10+b2 [49.4 kB]
Get:13 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 netbase all 5.4 [19.1 kB]
Get:14 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 less amd64 481-2.1 [126 kB]
Get:15 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libbsd0 amd64 0.8.3-1 [83.0 kB]
Get:16 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libncurses5 amd64 6.0+20161126-1+deb9u2 [93.4 kB]
Get:17 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libedit2 amd64 3.1-20160903-3 [84.8 kB]
Get:18 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libgpm2 amd64 1.20.4-6.2+b1 [34.2 kB]
Get:19 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 openssh-client amd64 1:7.4p1-10+deb9u6 [781 kB]
Get:20 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 javascript-common all 11 [6120 B]
Get:21 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libgmpxx4ldbl amd64 2:6.1.2+dfsg-1 [22.2 kB]
Get:22 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libgmp-dev amd64 2:6.1.2+dfsg-1 [631 kB]
Get:23 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libjs-jquery all 3.1.1-2+deb9u1 [154 kB]
Get:24 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libxdmcp6 amd64 1:1.1.2-3 [26.3 kB]
Get:25 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libxcb1 amd64 1.12-1 [133 kB]
Get:26 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libx11-data all 2:1.6.4-3+deb9u1 [287 kB]
Get:27 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libx11-6 amd64 2:1.6.4-3+deb9u1 [748 kB]
Get:28 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libxext6 amd64 2:1.3.3-1+b2 [52.5 kB]
Get:29 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libxmuu1 amd64 2:1.1.2-2 [23.5 kB]
Get:30 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libyaml-0-2 amd64 0.1.7-2 [47.6 kB]
Get:31 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 patch amd64 2.7.5-1+deb9u1 [112 kB]
Get:32 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 rubygems-integration all 1.11 [4994 B]
Get:33 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 ruby-did-you-mean all 1.0.0-2 [11.2 kB]
Get:34 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 ruby-minitest all 5.9.0-1 [51.1 kB]
Get:35 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 ruby-net-telnet all 0.1.1-2 [12.5 kB]
Get:36 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 ruby-power-assert all 0.3.0-1 [7902 B]
Get:37 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 ruby-test-unit all 3.1.7-2 [69.6 kB]
Get:38 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libruby2.3 amd64 2.3.3-1+deb9u6 [3109 kB]
Get:39 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 ruby2.3 amd64 2.3.3-1+deb9u6 [188 kB]
Get:40 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 ruby amd64 1:2.3.3 [10.8 kB]
Get:41 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 rake all 10.5.0-2 [49.4 kB]
Get:42 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 rename all 0.20-4 [12.5 kB]
Get:43 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 rsync amd64 3.1.2-1+deb9u2 [393 kB]
Get:44 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 ruby2.3-dev amd64 2.3.3-1+deb9u6 [1181 kB]
Get:45 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 ruby-dev amd64 1:2.3.3 [9574 B]
Get:46 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 unzip amd64 6.0-21+deb9u1 [170 kB]
Get:47 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 xauth amd64 1:1.0.9-1+b2 [39.6 kB]
Get:48 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 zip amd64 3.0-11+b1 [234 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 24.2 MB in 0s (43.5 MB/s)
Selecting previously unselected package perl-modules-5.24.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 7101 files and directories currently installed.)
Preparing to unpack .../00-perl-modules-5.24_5.24.1-3+deb9u5_all.deb ...
Unpacking perl-modules-5.24 (5.24.1-3+deb9u5) ...
Selecting previously unselected package libgdbm3:amd64.
Preparing to unpack .../01-libgdbm3_1.8.3-14_amd64.deb ...
Unpacking libgdbm3:amd64 (1.8.3-14) ...
Selecting previously unselected package libperl5.24:amd64.
Preparing to unpack .../02-libperl5.24_5.24.1-3+deb9u5_amd64.deb ...
Unpacking libperl5.24:amd64 (5.24.1-3+deb9u5) ...
Selecting previously unselected package perl.
Preparing to unpack .../03-perl_5.24.1-3+deb9u5_amd64.deb ...
Unpacking perl (5.24.1-3+deb9u5) ...
Selecting previously unselected package fonts-lato.
Preparing to unpack .../04-fonts-lato_2.0-1_all.deb ...
Unpacking fonts-lato (2.0-1) ...
Selecting previously unselected package libcurl3-gnutls:amd64.
Preparing to unpack .../05-libcurl3-gnutls_7.52.1-5+deb9u9_amd64.deb ...
Unpacking libcurl3-gnutls:amd64 (7.52.1-5+deb9u9) ...
Selecting previously unselected package libexpat1:amd64.
Preparing to unpack .../06-libexpat1_2.2.0-2+deb9u1_amd64.deb ...
Unpacking libexpat1:amd64 (2.2.0-2+deb9u1) ...
Selecting previously unselected package liberror-perl.
Preparing to unpack .../07-liberror-perl_0.17024-1_all.deb ...
Unpacking liberror-perl (0.17024-1) ...
Selecting previously unselected package git-man.
Preparing to unpack .../08-git-man_1%3a2.11.0-3+deb9u4_all.deb ...
Unpacking git-man (1:2.11.0-3+deb9u4) ...
Selecting previously unselected package git.
Preparing to unpack .../09-git_1%3a2.11.0-3+deb9u4_amd64.deb ...
Unpacking git (1:2.11.0-3+deb9u4) ...
Selecting previously unselected package libxau6:amd64.
Preparing to unpack .../10-libxau6_1%3a1.0.8-1_amd64.deb ...
Unpacking libxau6:amd64 (1:1.0.8-1) ...
Selecting previously unselected package libpopt0:amd64.
Preparing to unpack .../11-libpopt0_1.16-10+b2_amd64.deb ...
Unpacking libpopt0:amd64 (1.16-10+b2) ...
Selecting previously unselected package netbase.
Preparing to unpack .../12-netbase_5.4_all.deb ...
Unpacking netbase (5.4) ...
Selecting previously unselected package less.
Preparing to unpack .../13-less_481-2.1_amd64.deb ...
Unpacking less (481-2.1) ...
Selecting previously unselected package libbsd0:amd64.
Preparing to unpack .../14-libbsd0_0.8.3-1_amd64.deb ...
Unpacking libbsd0:amd64 (0.8.3-1) ...
Selecting previously unselected package libncurses5:amd64.
Preparing to unpack .../15-libncurses5_6.0+20161126-1+deb9u2_amd64.deb ...
Unpacking libncurses5:amd64 (6.0+20161126-1+deb9u2) ...
Selecting previously unselected package libedit2:amd64.
Preparing to unpack .../16-libedit2_3.1-20160903-3_amd64.deb ...
Unpacking libedit2:amd64 (3.1-20160903-3) ...
Selecting previously unselected package libgpm2:amd64.
Preparing to unpack .../17-libgpm2_1.20.4-6.2+b1_amd64.deb ...
Unpacking libgpm2:amd64 (1.20.4-6.2+b1) ...
Selecting previously unselected package openssh-client.
Preparing to unpack .../18-openssh-client_1%3a7.4p1-10+deb9u6_amd64.deb ...
Unpacking openssh-client (1:7.4p1-10+deb9u6) ...
Selecting previously unselected package javascript-common.
Preparing to unpack .../19-javascript-common_11_all.deb ...
Unpacking javascript-common (11) ...
Selecting previously unselected package libgmpxx4ldbl:amd64.
Preparing to unpack .../20-libgmpxx4ldbl_2%3a6.1.2+dfsg-1_amd64.deb ...
Unpacking libgmpxx4ldbl:amd64 (2:6.1.2+dfsg-1) ...
Selecting previously unselected package libgmp-dev:amd64.
Preparing to unpack .../21-libgmp-dev_2%3a6.1.2+dfsg-1_amd64.deb ...
Unpacking libgmp-dev:amd64 (2:6.1.2+dfsg-1) ...
Selecting previously unselected package libjs-jquery.
Preparing to unpack .../22-libjs-jquery_3.1.1-2+deb9u1_all.deb ...
Unpacking libjs-jquery (3.1.1-2+deb9u1) ...
Selecting previously unselected package libxdmcp6:amd64.
Preparing to unpack .../23-libxdmcp6_1%3a1.1.2-3_amd64.deb ...
Unpacking libxdmcp6:amd64 (1:1.1.2-3) ...
Selecting previously unselected package libxcb1:amd64.
Preparing to unpack .../24-libxcb1_1.12-1_amd64.deb ...
Unpacking libxcb1:amd64 (1.12-1) ...
Selecting previously unselected package libx11-data.
Preparing to unpack .../25-libx11-data_2%3a1.6.4-3+deb9u1_all.deb ...
Unpacking libx11-data (2:1.6.4-3+deb9u1) ...
Selecting previously unselected package libx11-6:amd64.
Preparing to unpack .../26-libx11-6_2%3a1.6.4-3+deb9u1_amd64.deb ...
Unpacking libx11-6:amd64 (2:1.6.4-3+deb9u1) ...
Selecting previously unselected package libxext6:amd64.
Preparing to unpack .../27-libxext6_2%3a1.3.3-1+b2_amd64.deb ...
Unpacking libxext6:amd64 (2:1.3.3-1+b2) ...
Selecting previously unselected package libxmuu1:amd64.
Preparing to unpack .../28-libxmuu1_2%3a1.1.2-2_amd64.deb ...
Unpacking libxmuu1:amd64 (2:1.1.2-2) ...
Selecting previously unselected package libyaml-0-2:amd64.
Preparing to unpack .../29-libyaml-0-2_0.1.7-2_amd64.deb ...
Unpacking libyaml-0-2:amd64 (0.1.7-2) ...
Selecting previously unselected package patch.
Preparing to unpack .../30-patch_2.7.5-1+deb9u1_amd64.deb ...
Unpacking patch (2.7.5-1+deb9u1) ...
Selecting previously unselected package rubygems-integration.
Preparing to unpack .../31-rubygems-integration_1.11_all.deb ...
Unpacking rubygems-integration (1.11) ...
Selecting previously unselected package ruby-did-you-mean.
Preparing to unpack .../32-ruby-did-you-mean_1.0.0-2_all.deb ...
Unpacking ruby-did-you-mean (1.0.0-2) ...
Selecting previously unselected package ruby-minitest.
Preparing to unpack .../33-ruby-minitest_5.9.0-1_all.deb ...
Unpacking ruby-minitest (5.9.0-1) ...
Selecting previously unselected package ruby-net-telnet.
Preparing to unpack .../34-ruby-net-telnet_0.1.1-2_all.deb ...
Unpacking ruby-net-telnet (0.1.1-2) ...
Selecting previously unselected package ruby-power-assert.
Preparing to unpack .../35-ruby-power-assert_0.3.0-1_all.deb ...
Unpacking ruby-power-assert (0.3.0-1) ...
Selecting previously unselected package ruby-test-unit.
Preparing to unpack .../36-ruby-test-unit_3.1.7-2_all.deb ...
Unpacking ruby-test-unit (3.1.7-2) ...
Selecting previously unselected package libruby2.3:amd64.
Preparing to unpack .../37-libruby2.3_2.3.3-1+deb9u6_amd64.deb ...
Unpacking libruby2.3:amd64 (2.3.3-1+deb9u6) ...
Selecting previously unselected package ruby2.3.
Preparing to unpack .../38-ruby2.3_2.3.3-1+deb9u6_amd64.deb ...
Unpacking ruby2.3 (2.3.3-1+deb9u6) ...
Selecting previously unselected package ruby.
Preparing to unpack .../39-ruby_1%3a2.3.3_amd64.deb ...
Unpacking ruby (1:2.3.3) ...
Selecting previously unselected package rake.
Preparing to unpack .../40-rake_10.5.0-2_all.deb ...
Unpacking rake (10.5.0-2) ...
Selecting previously unselected package rename.
Preparing to unpack .../41-rename_0.20-4_all.deb ...
Unpacking rename (0.20-4) ...
Selecting previously unselected package rsync.
Preparing to unpack .../42-rsync_3.1.2-1+deb9u2_amd64.deb ...
Unpacking rsync (3.1.2-1+deb9u2) ...
Selecting previously unselected package ruby2.3-dev:amd64.
Preparing to unpack .../43-ruby2.3-dev_2.3.3-1+deb9u6_amd64.deb ...
Unpacking ruby2.3-dev:amd64 (2.3.3-1+deb9u6) ...
Selecting previously unselected package ruby-dev:amd64.
Preparing to unpack .../44-ruby-dev_1%3a2.3.3_amd64.deb ...
Unpacking ruby-dev:amd64 (1:2.3.3) ...
Selecting previously unselected package unzip.
Preparing to unpack .../45-unzip_6.0-21+deb9u1_amd64.deb ...
Unpacking unzip (6.0-21+deb9u1) ...
Selecting previously unselected package xauth.
Preparing to unpack .../46-xauth_1%3a1.0.9-1+b2_amd64.deb ...
Unpacking xauth (1:1.0.9-1+b2) ...
Selecting previously unselected package zip.
Preparing to unpack .../47-zip_3.0-11+b1_amd64.deb ...
Unpacking zip (3.0-11+b1) ...
Setting up libncurses5:amd64 (6.0+20161126-1+deb9u2) ...
Setting up libjs-jquery (3.1.1-2+deb9u1) ...
Setting up perl-modules-5.24 (5.24.1-3+deb9u5) ...
Setting up libgdbm3:amd64 (1.8.3-14) ...
Setting up libperl5.24:amd64 (5.24.1-3+deb9u5) ...
Setting up git-man (1:2.11.0-3+deb9u4) ...
Setting up libpopt0:amd64 (1.16-10+b2) ...
Setting up libexpat1:amd64 (2.2.0-2+deb9u1) ...
Setting up less (481-2.1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Setting up libgpm2:amd64 (1.20.4-6.2+b1) ...
Setting up libcurl3-gnutls:amd64 (7.52.1-5+deb9u9) ...
Setting up unzip (6.0-21+deb9u1) ...
Setting up libbsd0:amd64 (0.8.3-1) ...
Setting up zip (3.0-11+b1) ...
Setting up rsync (3.1.2-1+deb9u2) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of restart.
Setting up fonts-lato (2.0-1) ...
Setting up perl (5.24.1-3+deb9u5) ...
update-alternatives: using /usr/bin/prename to provide /usr/bin/rename (rename) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/rename.1.gz because associated file /usr/share/man/man1/prename.1.gz (of link group rename) doesn't exist
Setting up ruby-did-you-mean (1.0.0-2) ...
Setting up libyaml-0-2:amd64 (0.1.7-2) ...
Setting up patch (2.7.5-1+deb9u1) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Setting up ruby-net-telnet (0.1.1-2) ...
Setting up rubygems-integration (1.11) ...
Setting up libxdmcp6:amd64 (1:1.1.2-3) ...
Setting up javascript-common (11) ...
Setting up libgmpxx4ldbl:amd64 (2:6.1.2+dfsg-1) ...
Setting up ruby-minitest (5.9.0-1) ...
Setting up libx11-data (2:1.6.4-3+deb9u1) ...
Setting up libxau6:amd64 (1:1.0.8-1) ...
Setting up ruby-power-assert (0.3.0-1) ...
Setting up netbase (5.4) ...
Setting up libedit2:amd64 (3.1-20160903-3) ...
Setting up libgmp-dev:amd64 (2:6.1.2+dfsg-1) ...
Setting up ruby-test-unit (3.1.7-2) ...
Setting up liberror-perl (0.17024-1) ...
Setting up rename (0.20-4) ...
update-alternatives: using /usr/bin/file-rename to provide /usr/bin/rename (rename) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/rename.1.gz because associated file /usr/share/man/man1/file-rename.1p.gz (of link group rename) doesn't exist
Setting up openssh-client (1:7.4p1-10+deb9u6) ...
Setting up libxcb1:amd64 (1.12-1) ...
Setting up git (1:2.11.0-3+deb9u4) ...
Setting up libx11-6:amd64 (2:1.6.4-3+deb9u1) ...
Setting up libxmuu1:amd64 (2:1.1.2-2) ...
Setting up libxext6:amd64 (2:1.3.3-1+b2) ...
Setting up xauth (1:1.0.9-1+b2) ...
Setting up ruby2.3 (2.3.3-1+deb9u6) ...
Setting up ruby (1:2.3.3) ...
Setting up rake (10.5.0-2) ...
Setting up libruby2.3:amd64 (2.3.3-1+deb9u6) ...
Setting up ruby2.3-dev:amd64 (2.3.3-1+deb9u6) ...
Setting up ruby-dev:amd64 (1:2.3.3) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
$ gem install dpl
Successfully installed dpl-1.10.8
Parsing documentation for dpl-1.10.8
Installing ri documentation for dpl-1.10.8
Done installing documentation for dpl after 0 seconds
1 gem installed
$ dpl --provider=heroku --app=fero-dev-frontend --strategy=git --username=$HEROKU_USER --password=$HEROKU_PASSWORD --api-key=$HEROKU_STAGING_API_KEY
Installing deploy dependencies
Successfully installed multipart-post-2.1.1
Successfully installed faraday-0.15.4
Successfully installed rendezvous-0.1.3
Successfully installed netrc-0.11.0
Successfully installed dpl-heroku-1.10.8
Parsing documentation for multipart-post-2.1.1
Installing ri documentation for multipart-post-2.1.1
Parsing documentation for faraday-0.15.4
Installing ri documentation for faraday-0.15.4
Parsing documentation for rendezvous-0.1.3
Installing ri documentation for rendezvous-0.1.3
Parsing documentation for netrc-0.11.0
Installing ri documentation for netrc-0.11.0
Parsing documentation for dpl-heroku-1.10.8
Installing ri documentation for dpl-heroku-1.10.8
Done installing documentation for multipart-post, faraday, rendezvous, netrc, dpl-heroku after 1 seconds
5 gems installed
authentication succeeded
checking for app fero-dev-frontend
found app fero-dev-frontend
Preparing deploy
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment#Uploading-Files-and-skip_cleanup.
No local changes to save
$ git fetch origin $TRAVIS_BRANCH --unshallow
Deploying application
fatal: --unshallow on a complete repository does not make sense
$ git push https://git.heroku.com/fero-dev-frontend.git HEAD:refs/heads/master -f
remote: Compressing source files... done.        
remote: Building source:        
remote: 
remote: -----> Node.js app detected        
remote:                
remote: -----> Creating runtime environment        
remote:                
remote:        NPM_CONFIG_LOGLEVEL=error        
remote:        NODE_ENV=production        
remote:        NODE_MODULES_CACHE=true        
remote:        NODE_VERBOSE=false        
remote:                
remote: -----> Installing binaries        
remote:        engines.node (package.json):  ^11.6.0        
remote:        engines.npm (package.json):   unspecified (use default)        
remote:        engines.yarn (package.json):  ^1.12.3        
remote:                
remote:        Resolving node version ^11.6.0...        
remote:        Downloading and installing node 11.15.0...        
remote:        Using default npm version: 6.7.0        
remote:        Resolving yarn version ^1.12.3...        
remote:        Downloading and installing yarn (1.16.0)...        
remote:        Installed yarn 1.16.0        
remote:                
remote: -----> Restoring cache        
remote:        - node_modules        
remote:                
remote: -----> Installing dependencies        
remote:        Installing node modules (yarn.lock)        
remote:        yarn install v1.16.0        
remote:        [1/4] Resolving packages...        
remote:        success Already up-to-date.        
remote:        $ node scripts/build.js        
remote:        Creating an optimized production build...        
remote:        /tmp/build_6cb533262986eef723837f440174028e/scripts/build.js:11        
remote:          throw err;        
remote:          ^        
remote:                
remote:        Error: Command failed: /tmp/build_6cb533262986eef723837f440174028e/node_modules/@sentry/cli/sentry-cli releases propose-version        
remote:          INFO    2019-05-26 07:42:47.951847353 +00:00 Loaded config from /app/.sentryclirc        
remote:          DEBUG   2019-05-26 07:42:47.951917088 +00:00 sentry-cli version: 1.39.1, platform: "linux", architecture: "x86_64"        
remote:          INFO    2019-05-26 07:42:47.951944240 +00:00 sentry-cli was invoked with the following command line: "/tmp/build_6cb533262986eef723837f440174028e/node_modules/@sentry/cli/sentry-cli" "releases" "propose-version"        
remote:          DEBUG   2019-05-26 07:42:47.952141953 +00:00 error: running update nagger        
remote:          DEBUG   2019-05-26 07:42:47.952163689 +00:00 skipping update nagger because session is not attended        
remote:        error: Could not automatically determine release name        
remote:          DEBUG   2019-05-26 07:42:47.954922406 +00:00 client close; no transport to shut down  (from sentry)        
remote:                
remote:            at ChildProcess.exithandler (child_process.js:299:12)        
remote:            at ChildProcess.emit (events.js:193:13)        
remote:            at maybeClose (internal/child_process.js:999:16)        
remote:            at Socket.stream.socket.on (internal/child_process.js:403:11)        
remote:            at Socket.emit (events.js:193:13)        
remote:            at Pipe._handle.close (net.js:614:12)        
remote:        error Command failed with exit code 1.        
remote:        info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.        
remote: 
remote: -----> Build failed        
remote:                
remote:        We're sorry this build is failing! You can troubleshoot common issues here:        
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys        
remote:                
remote:        If you're stuck, please submit a ticket so we can help:        
remote:        https://help.heroku.com/        
remote:                
remote:        Love,        
remote:        Heroku        
remote:                
remote:  !     Push rejected, failed to compile Node.js app.        
remote: 
remote:  !     Push failed        
remote: Verifying deploy...
remote: 
remote: !	Push rejected to fero-dev-frontend.        
remote: 
To https://git.heroku.com/fero-dev-frontend.git
 ! [remote rejected] HEAD -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/fero-dev-frontend.git'
No stash found.
Job succeeded
```

**Comment by prem-prakash** [comment]
same problem here

**Comment by kamilogorek** [comment]
Already fixed in October https://github.com/getsentry/sentry-cli/blob/39da2f7f8102f7f9b5ddf83b0de89344d9016789/src/utils/releases.rs#L93-L105
