### ISSUE TITLE
Panic on None value in libcore/option when setting commits on Release

### ISSUE THREAD

**Issue by ryanwilsonperkin** [getsentry/sentry-cli#561]
We saw the following error when running `sentry-cli releases --org ORG_ID set-commits RELEASE_ID --auto`:

```rust
thread 'unnamed' panicked at 'called `Option::unwrap()` on a `None` value': libcore/option.rs:355

stack backtrace:
   0: sentry_cli::utils::system::init_backtrace::{{closure}}::h829e24a89b7a5fb0 (0x4fb33f)
   1: sentry::integrations::panic::register_panic_handler::{{closure}}::h4845b71a44af0d1d (0x828ca2)
   2: std::panicking::rust_panic_with_hook::hb4c40b3721cfbfb0 (0xd3f206)
             at libstd/panicking.rs:480
   3: std::panicking::continue_panic_fmt::h7e84a0a182ce9c2d (0xd3ed51)
             at libstd/panicking.rs:390
   4: rust_begin_unwind (0xd3ec35)
             at libstd/panicking.rs:325
   5: core::panicking::panic_fmt::h0c93626b89c38af6 (0xd77e4c)
             at libcore/panicking.rs:77
   6: core::panicking::panic::h158c6e3285d6c3fb (0xd77d7b)
             at libcore/panicking.rs:52
   7: git2::submodule::Submodule::url::ha3581002dbf01726 (0x604de1)
   8: sentry_cli::utils::vcs::find_matching_rev::h5395ac0407631570 (0x52b5c4)
   9: sentry_cli::utils::vcs::find_heads::h77f9391605aece2f (0x52d9ce)
  10: sentry_cli::commands::releases::execute::h810d3f06aadc0dac (0x4e5721)
  11: sentry_cli::commands::run_command::h4163cacefb823ce4 (0x51ec42)
  12: sentry_cli::commands::main::h9fb587bbfc861a27 (0x524b95)
  13: std::sys_common::backtrace::__rust_begin_short_backtrace::hcaec43099d9a32b2 (0x46c41e)
  14: __rust_maybe_catch_panic (0xd4ea29)
             at libpanic_unwind/lib.rs:102
  15: <F as alloc::boxed::FnBox<A>>::call_box::h2e7cbb2dba0e3ca8 (0x49a8eb)
  16: <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::hb2472c460769f74d (0xd3d8ad)
             at liballoc/boxed.rs:682
      std::sys_common::thread::start_thread::hba2b092b2e82ea48
             at libstd/sys_common/thread.rs:24
  17: std::sys::unix::thread::Thread::new::thread_start::hba5ef65a9b43a615 (0xd27dd5)
             at libstd/sys/unix/thread.rs:90

```

I unfortunately don't have debugging mode enabled on the system that generated this backtrace but am including it in case it is helpful.

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
