### ISSUE TITLE
ENOTFOUND downloads.sentry-cdn.com downloads.sentry-cdn.com:443

### ISSUE THREAD

**Issue by bhandaribhumin** [getsentry/sentry-cli#608]
I try to install sentry cli terminal give me error. 
System details: MacOS catalina 10.15 
 npm -v : 6.9.0
node -v : v10.16.3

NOTE: I'm in proxy server already set proxy in npm and git.

> npm install @sentry/cli --verbose

```
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '@sentry/cli',
npm verb cli   '--verbose' ]
npm info using npm@6.9.0
npm info using node@v10.16.3
npm verb npm-session 685748e341203be0
npm http fetch GET 304 https://registry.npmjs.org/@sentry%2fcli 541ms (from cache)
npm timing stage:loadCurrentTree Completed in 8203ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 12ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 312ms
npm http fetch GET 304 https://registry.npmjs.org/proxy-from-env 287ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-copy-file-sync 305ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/https-proxy-agent 306ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/progress 310ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/debug 5ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/agent-base 322ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/es6-promisify 294ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/es6-promise 294ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ms 273ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 2639ms
npm timing stage:loadIdealTree Completed in 3228ms
npm timing stage:generateActionsToTake Completed in 61ms
npm verb correctMkdir /Users/bhuminbhandari/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/bhuminbhandari/.npm/_locks/staging-916015cb214171e3.lock for /Users/bhuminbhandari/Desktop/projects/xyz/node_modules/.staging
npm timing action:extract Completed in 73ms
npm timing action:finalize Completed in 17ms
npm timing action:refresh-package-json Completed in 24ms
npm info lifecycle es6-promise@4.2.8~preinstall: es6-promise@4.2.8
npm info lifecycle es6-promisify@5.0.0~preinstall: es6-promisify@5.0.0
npm info lifecycle agent-base@4.3.0~preinstall: agent-base@4.3.0
npm info lifecycle ms@2.1.2~preinstall: ms@2.1.2
npm info lifecycle debug@3.2.6~preinstall: debug@3.2.6
npm info lifecycle fs-copy-file-sync@1.1.1~preinstall: fs-copy-file-sync@1.1.1
npm info lifecycle https-proxy-agent@3.0.0~preinstall: https-proxy-agent@3.0.0
npm info lifecycle progress@2.0.0~preinstall: progress@2.0.0
npm info lifecycle proxy-from-env@1.0.0~preinstall: proxy-from-env@1.0.0
npm info lifecycle @sentry/cli@1.48.0~preinstall: @sentry/cli@1.48.0
npm timing action:preinstall Completed in 5ms
npm info linkStuff es6-promise@4.2.8
npm info linkStuff es6-promisify@5.0.0
npm info linkStuff agent-base@4.3.0
npm info linkStuff ms@2.1.2
npm info linkStuff debug@3.2.6
npm info linkStuff fs-copy-file-sync@1.1.1
npm info linkStuff https-proxy-agent@3.0.0
npm info linkStuff progress@2.0.0
npm info linkStuff proxy-from-env@1.0.0
npm info linkStuff @sentry/cli@1.48.0
npm verb linkBins [ { 'sentry-cli': 'bin/sentry-cli' },
npm verb linkBins   '/Users/bhuminbhandari/Desktop/projects/xyz/node_modules/.bin',
npm verb linkBins   false ]
npm timing action:build Completed in 8ms
npm info lifecycle es6-promise@4.2.8~install: es6-promise@4.2.8
npm info lifecycle es6-promisify@5.0.0~install: es6-promisify@5.0.0
npm info lifecycle agent-base@4.3.0~install: agent-base@4.3.0
npm info lifecycle ms@2.1.2~install: ms@2.1.2
npm info lifecycle debug@3.2.6~install: debug@3.2.6
npm info lifecycle fs-copy-file-sync@1.1.1~install: fs-copy-file-sync@1.1.1
npm info lifecycle https-proxy-agent@3.0.0~install: https-proxy-agent@3.0.0
npm info lifecycle progress@2.0.0~install: progress@2.0.0
npm info lifecycle proxy-from-env@1.0.0~install: proxy-from-env@1.0.0
npm info lifecycle @sentry/cli@1.48.0~install: @sentry/cli@1.48.0

> @sentry/cli@1.48.0 install /Users/bhuminbhandari/Desktop/projects/xyznode_modules/@sentry/cli
> node scripts/install.js

FetchError: request to https://downloads.sentry-cdn.com/sentry-cli/1.48.0/sentry-cli-Darwin-x86_64 failed, reason: getaddrinfo ENOTFOUND downloads.sentry-cdn.com downloads.sentry-cdn.com:443
npm verb lifecycle @sentry/cli@1.48.0~install: unsafe-perm in lifecycle true
npm verb lifecycle @sentry/cli@1.48.0~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/bhuminbhandari/Desktop/projects/xyz/node_modules/@sentry/cli/node_modules/.bin:/Users/bhuminbhandari/Desktop/projects/xyz/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Apple/bin
npm verb lifecycle @sentry/cli@1.48.0~install: CWD: /Users/bhuminbhandari/Desktop/projectsxyz/node_modules/@sentry/cli
npm info lifecycle @sentry/cli@1.48.0~install: Failed to exec install script
npm timing action:install Completed in 258ms
npm verb unlock done using /Users/bhuminbhandari/.npm/_locks/staging-916015cb214171e3.lock for /Users/bhuminbhandari/Desktop/projects/xyz/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 28ms
npm timing stage:runTopLevelLifecycles Completed in 12220ms
npm WARN @auth0/angular-jwt@2.1.2 requires a peer of @angular/common@>=6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/badge@5.15.0 requires a peer of @ionic-native/core@^5.1.0 but none is installed. You must install peer dependencies yourself.

npm verb stack Error: @sentry/cli@1.48.0 install: `node scripts/install.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:198:13)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:198:13)
npm verb stack     at maybeClose (internal/child_process.js:982:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm verb pkgid @sentry/cli@1.48.0
npm verb cwd /Users/bhuminbhandari/Desktop/projects/xyz
npm verb Darwin 19.0.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@sentry/cli" "--verbose"
npm verb node v10.16.3
npm verb npm  v6.9.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sentry/cli@1.48.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @sentry/cli@1.48.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing audit submit Completed in 1069ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 1069ms
npm timing audit body Completed in 1ms
npm timing npm Completed in 13273ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bhuminbhandari/.npm/_logs/2019-10-15T07_04_05_348Z-debug.log
```

**Comment by kamilogorek** [comment]
I just verified it locally and it installs just fine when using versions you provided. Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
