### ISSUE TITLE
set-commits fails intermittently

### ISSUE THREAD

**Issue by thomasheartman** [getsentry/sentry-cli#701]
Hi! 

First off, not sure whether this goes to the community forums or here, but the more I flesh this out, the more it feels like a bug. Feel free to tell me otherwise if you disagree.

# Problem

I've got an issue where the `set-commits` command of the Sentry-CLI fails fairly often, but not always. We run it from CI on our self-hosted GitLab server, and this goes both for the pure CLI version and the webpack plugin. We use on on-prem Sentry solution.

Because it only fails sometimes, I can't reproduce it reliably, and right now, I'm unable to trigger an error with debug level logging. However, here's the error log I do get (log level: info):

```
> Analyzing 3 sources
> Rewriting sources
> Adding source map references
> Bundled 3 files for upload
> Uploaded release files to Sentry
error: API request failed
  caused by: [56] Failure when receiving data from the peer
(node:261) UnhandledPromiseRejectionWarning: Error: Command failed: /builds/<group>/<subgroup>/<project>/node_modules/@sentry/cli/sentry-cli releases set-commits vmprov@a37b3c23dc81f9604b8d9be211ac2c3d8a885d09 --auto
  INFO    2020-03-27 16:56:34.398052283 +00:00 Loaded config from /builds/<group>/<subgroup>/<project>/.sentryclirc
  INFO    2020-03-27 16:56:34.398113291 +00:00 sentry-cli was invoked with the following command line: "/builds/<group>/<subgroup>/<project>/node_modules/@sentry/cli/sentry-cli" "releases" "set-commits" "vmprov@a37b3c23dc81f9604b8d9be211ac2c3d8a885d09" "--auto"
  INFO    2020-03-27 16:56:34.453539552 +00:00 Resolving HEAD (<other project>@HEAD)
  INFO    2020-03-27 16:56:34.458569383 +00:00 Resolving HEAD (<this project>@HEAD)
  INFO    2020-03-27 16:56:34.458912792 +00:00   -> found matching revision a37b3c23dc81f9604b8d9be211ac2c3d8a885d09
error: API request failed
  caused by: [56] Failure when receiving data from the peer
    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1026:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:261) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:261) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It's the same error that appears every time:
```
error: API request failed
  caused by: [56] Failure when receiving data from the peer
```
But I don't know what to do about it.

-----

Anything more I can supply, just let me know.

Thanks!

**Comment by kamilogorek** [comment]
Hey. cURL error code 56 means that there was a problem with the server itself, not the client/receiver, see: https://curl.haxx.se/libcurl/c/libcurl-errors.html

```
CURLE_RECV_ERROR (56)
Failure with receiving network data.
```

Thus it's the issue with misconfigured on-prem instance and not the CLI itself.
I'll move the issue to https://github.com/getsentry/sentry/ repository and please ask there.

Also, running with `--log-level=debug` or `[log] level = debug` (in ini config file) fill definitely be helpful here, as you'll be able to tell which endpoint specifically failed.
