### ISSUE TITLE
npm install fails 1.10.0 and 1.10.1

### ISSUE THREAD

**Issue by w9jds** [getsentry/sentry-cli#73]
I can't install the cli on my windows 10 machine, I receive this error on trying to install it:
```
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\tmp\debug.log'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1314:33)
    at downloadBinary (C:\Users\w9jds\AppData\Roaming\npm\node_modules\sentry-cli-binary\bin\install-sentry-cli:52:17)
    at ClientRequest.handleResponse (C:\Users\w9jds\AppData\Roaming\npm\node_modules\sentry-cli-binary\bin\install-sentry-cli:117:5)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:522:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:411:20)
```

If I do @1.9.2 it worked just fine. The release *.exe also fails to do anything, it actually just silently crashes with it just flickering on the screen so fast you can barely tell it even started.

**Comment by mitsuhiko** [comment]
This is solved in 1.10.2.
