### ISSUE TITLE
broken npm install 1.53.0 using Azure image: macOS-10.14

### ISSUE THREAD

**Issue by chriscamac** [getsentry/sentry-cli#744]
receiving this error in my npm install pipeline when running an npm install task on Azure pipelines using the image: macOS-10.14.  This step works fine if I run ```npm i``` from my local windows setup.

By searching through your issues, I found that this has happened in the past and was resolved.  i.e. https://github.com/getsentry/sentry-cli/issues/307

```
170371 verbose stack Error: @sentry/cli@1.53.0 install: `node scripts/install.js`
170371 verbose stack Exit status 1
170371 verbose stack     at EventEmitter.<anonymous> (/usr/local/Cellar/node@6/6.17.0/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
170371 verbose stack     at emitTwo (events.js:106:13)
170371 verbose stack     at EventEmitter.emit (events.js:191:7)
170371 verbose stack     at ChildProcess.<anonymous> (/usr/local/Cellar/node@6/6.17.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
170371 verbose stack     at emitTwo (events.js:106:13)
170371 verbose stack     at ChildProcess.emit (events.js:191:7)
170371 verbose stack     at maybeClose (internal/child_process.js:920:16)
170371 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
```

**Comment by chriscamac** [comment]
I was able to fix this by setting the version of node to 10.19.0.  Probably doesn't have to be this version, but the version that Azure Pipelines was using by default was 6.17.0 and that definitely breaks the install.  I verified this by setting my node version locally to 6.17.0 and getting the same errors on npm install step.

For anyone else that might be working with Azure Pipelines and needs to know how specifically to fix this, here is a guide I followed for setting the node version in your Azure Pipeline https://mariusschulz.com/blog/setting-the-node-js-version-for-an-azure-devops-build
