### ISSUE TITLE
error: failed to invoke sentry-cli

### ISSUE THREAD

**Issue by josh-m-sharpe** [getsentry/sentry-cli#752]
Seems like I'm running into [this issue](https://github.com/getsentry/sentry-react-native/issues/323) which was swept under the rug over a year ago.

**Comment by josh-m-sharpe** [comment]
And this issue:
https://github.com/getsentry/sentry-cli/issues/407

**Comment by kamilogorek** [comment]
Do you have any more details? Logs? It's hard to even start debugging without it.

**Comment by rahamin1** [comment]
#### Using yarn on Windows 10 -and- "@sentry/react-native": "^1.7.2",

### The error (there is a similar output for _1001, _2001, _4001:
```
> Task :app:bundleReleaseJsAndAssets_SentryUpload_3001
error: failed to invoke sentry-cli
Error: spawn C:\esites-grocery\plumpclient\node_modules\@sentry\cli\sentry-cli.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

### My environment

```
System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 3.24 GB / 15.87 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 25.0.2, 28.0.3, 29.0.2, 29.0.3
      System Images: android-25 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  2.3.0.0 AI-162.3764568
  Languages:
    Java: 1.8.0_112-release
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
```

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by bjornegil** [comment]
Had the same issue (@sentry/react-native: 1.9.0, react-native: 0.63.3). 
```
npm uninstall @sentry/react-native
npm install @sentry/react-native@2.5.1
```

seemed to fix it.

Could possibly have fixed it just doing uninstall and install of same version.
