### ISSUE TITLE
Cannot install v1.13.2

### ISSUE THREAD

**Issue by kevynb** [getsentry/sentry-cli#78]
Hello,

When I try to install sentry cli through npm I've got the following error:
```
> sentry-cli-binary@1.13.2 install */node_modules/sentry-cli-binary
> node ./bin/install-sentry-cli

*/node_modules/sentry-cli-binary/bin/install-sentry-cli:20
if platform === 'win32' {
   ^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:537:3
```

I think you forgot some () 😄 

Cheers!

**Comment by Jolg42** [comment]
Same for me with Node.js v4.3.1 on macOS Sierra
So I'm stuck on version 1.4.1 (That is working fine)

**Comment by robertmerten** [comment]
We are currently unable to update / install react-native-sentry because the install fails when the syntax error occurs.

**Comment by mitsuhiko** [comment]
This should work fine now.
