### ISSUE TITLE
Yarn/npm install failed for 1.55 - reason: connect ECONNREFUSED 0.0.0.0:443

### ISSUE THREAD

**Issue by G07cha** [getsentry/sentry-cli#786]
Full error:

```
FetchError: request to https://downloads.sentry-cdn.com/sentry-cli/1.55.0/sentry-cli-Darwin-x86_64 failed, reason: connect ECONNREFUSED 0.0.0.0:443
```

yarn-error.log:

```
Yarn version: 
  1.22.4

Node version: 
  12.16.2

Platform: 
  darwin x64

Trace: 
  Error: canceled
      at Interface.<anonymous> (/usr/local/var/yvm/versions/v1.22.4/lib/cli.js:137008:13)
      at Interface.emit (events.js:310:20)
      at Interface._ttyWrite (readline.js:893:16)
      at ReadStream.onkeypress (readline.js:198:10)
      at ReadStream.emit (events.js:310:20)
      at emitKeys (internal/readline/utils.js:438:14)
      at emitKeys.next (<anonymous>)
      at ReadStream.onData (readline.js:1160:36)
      at ReadStream.emit (events.js:310:20)
      at addChunk (_stream_readable.js:286:12)

npm manifest: 
  No manifest

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile
```

**Comment by G07cha** [comment]
Nevermind, it's something with my network
