### ISSUE TITLE
404 error when install sentry cli.

### ISSUE THREAD

**Issue by Fnxxxxo** [getsentry/sentry-cli#807]
I meet an 404 error when installing @sentry/webpack-plugin on Jenkins.
```
verbose 37.742 Copying "/usr/local/share/.cache/yarn/v6/npm-vue-2.6.11-76594d877d4b12234406e84e35275c6d514125c5-integrity/node_modules/vue/src/platforms/weex/compiler/modules/recycle-list/v-once.js" to "/var/jenkins_home/workspace/docker-test-build-cms-static/node_modules/vue/src/platforms/weex/compiler/modules/recycle-list/v-once.js".
verbose 37.753 Creating symlink at "/var/jenkins_home/workspace/docker-test-build-cms-static/node_modules/@scrm/cms" to "/var/jenkins_home/workspace/docker-test-build-cms-static/packages/cms-frontier".
verbose 37.754 Creating symlink at "/var/jenkins_home/workspace/docker-test-build-cms-static/node_modules/demo" to "/var/jenkins_home/workspace/docker-test-build-cms-static/packages/demo".
[4/4] Building fresh packages...
verbose 41.231 [35m[1mLove Swiper? Support Vladimir's work by donating or pledging on patreon:[22m[39m
 > [32mhttps://patreon.com/vladimirkharlampidi[0m
verbose 42.128 
verbose 42.787 
verbose 42.806 Thank you for installing [35mEJS[0m: built with the [32mJake[0m JavaScript build tool ([32mhttps://jakejs.com/[0m)
verbose 42.828 Error: /var/jenkins_home/workspace/docker-test-build-cms-static/node_modules/@sentry/cli: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments: 
Directory: /var/jenkins_home/workspace/docker-test-build-cms-static/node_modules/@sentry/cli
Output:
Error: Received 404: Not Found
    at ProcessTermError.ExtendableBuiltin (/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/jenkins-node/lib/node_modules/yarn/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/jenkins-node/lib/node_modules/yarn/lib/cli.js:750:123)
    at new ProcessTermError (/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/jenkins-node/lib/node_modules/yarn/lib/cli.js:790:113)
    at ChildProcess.<anonymous> (/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/jenkins-node/lib/node_modules/yarn/lib/cli.js:25884:17)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
error /var/jenkins_home/workspace/docker-test-build-cms-static/node_modules/@sentry/cli: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments: 
Directory: /var/jenkins_home/workspace/docker-test-build-cms-static/node_modules/@sentry/cli
Output:
Error: Received 404: Not Found
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
verbose 42.992 Thank you for using ant-design-vue ( https://github.com/vueComponent/ant-design-vue )!
```
The error remains when I do a clean install with sentrycli_cdnurl config.
Any why to fix it?

**Comment by kamilogorek** [comment]
It looks like a connection issue between our CDN and your Jenkins instance. You can try to use GitHub releases as the mirror to verify this:

```terminal
SENTRYCLI_CDNURL=https://github.com/getsentry/sentry-cli/releases/download/ npm install @sentry/cli
```

**Comment by Fnxxxxo** [comment]
@kamilogorek Resolved. Thanks.
