### ISSUE TITLE
Fails with npx

### ISSUE THREAD

**Issue by travigd** [getsentry/sentry-cli#820]
I'm not sure if this is an entry with this package in particular, but it seems to work for other things (I tried with create-react-app just to see), so I'm posting here.

I'm running in CI, in a container with image `node:12-slim@sha256:6ef3d2ceb4b0da8a3c618f773c9e8c5995633711ee49ddb811d0d57cbea7d95c` (and I could reproduce this with the same image on my laptop);
```sh
# npx sentry-cli 
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/8/lib/node_modules/sentry-cli/tasks/download.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sentry-cli@0.0.4 postinstall: `node tasks/download.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sentry-cli@0.0.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-10T22_56_04_671Z-debug.log
Install for [ 'sentry-cli@latest' ] failed with code 1
```

The output from the log file doesn't look extraordinary:
```
...
2990 verbose lifecycle sentry-cli@0.0.4~postinstall: unsafe-perm in lifecycle false
2991 verbose lifecycle sentry-cli@0.0.4~postinstall: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/.npm/_npx/8/lib/node_modules/sentry-cli/node_modules/.bin:/root/.npm/_npx/8/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2992 verbose lifecycle sentry-cli@0.0.4~postinstall: CWD: /root/.npm/_npx/8/lib/node_modules/sentry-cli
2993 silly lifecycle sentry-cli@0.0.4~postinstall: Args: [ '-c', 'node tasks/download.js' ]
2994 silly lifecycle sentry-cli@0.0.4~postinstall: Returned: code: 1  signal: null
2995 info lifecycle sentry-cli@0.0.4~postinstall: Failed to exec postinstall script
2996 timing action:postinstall Completed in 133ms
2997 verbose unlock done using /root/.npm/_locks/staging-aa1ad98389d426fc.lock for /root/.npm/_npx/8/lib/node_modules/.staging
2998 timing stage:rollbackFailedOptional Completed in 130ms
2999 timing stage:runTopLevelLifecycles Completed in 4327ms
3000 verbose stack Error: sentry-cli@0.0.4 postinstall: `node tasks/download.js`
3000 verbose stack Exit status 1
3000 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
3000 verbose stack     at EventEmitter.emit (events.js:311:20)
3000 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
3000 verbose stack     at ChildProcess.emit (events.js:311:20)
3000 verbose stack     at maybeClose (internal/child_process.js:1021:16)
3000 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
3001 verbose pkgid sentry-cli@0.0.4
3002 verbose cwd /
3003 verbose Linux 4.19.76-linuxkit
3004 verbose argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "install" "sentry-cli@latest" "--global" "--prefix" "/root/.npm/_npx/8" "--loglevel" "error" "--json"
3005 verbose node v12.16.1
3006 verbose npm  v6.13.4
3007 error code ELIFECYCLE
3008 error errno 1
3009 error sentry-cli@0.0.4 postinstall: `node tasks/download.js`
3009 error Exit status 1
3010 error Failed at the sentry-cli@0.0.4 postinstall script.
3010 error This is probably not a problem with npm. There is likely additional logging output above.
3011 verbose exit [ 1, true ]
```

It works if I just `npm i -g sentry-cli` instead of using npx.

**Comment by kamilogorek** [comment]
You are trying to install incorrect package. `npx @sentry/cli <command>`.
Cheers! :)
