### ISSUE TITLE
npm install fails in github action

### ISSUE THREAD

**Issue by leemhenson** [getsentry/sentry-cli#838]
Hi. I'm using the sentry webpack plugin and thus the sentry cli package is a dependency too. Running locally everything works as expected. But when I push to github, a custom action kicks off which takes 6 hours to run and then dies. All it is doing is running `npm install`. I don't actually invoke sentry in the github action in any way.

Here's the log output:

```
installing NPM dependencies
npm at "/usr/local/bin/npm"
/usr/local/bin/npm ci

> @sentry/cli@1.58.0 install /home/runner/work/smol/smol/customer-api/node_modules/@sentry/cli
> node scripts/install.js

fetching sentry-cli-Linux-x86_64 1%
fetching sentry-cli-Linux-x86_64 2%
fetching sentry-cli-Linux-x86_64 3%
fetching sentry-cli-Linux-x86_64 4%
fetching sentry-cli-Linux-x86_64 5%
fetching sentry-cli-Linux-x86_64 6%
fetching sentry-cli-Linux-x86_64 7%
fetching sentry-cli-Linux-x86_64 8%
fetching sentry-cli-Linux-x86_64 9%
fetching sentry-cli-Linux-x86_64 10%
fetching sentry-cli-Linux-x86_64 11%
fetching sentry-cli-Linux-x86_64 12%
fetching sentry-cli-Linux-x86_64 13%
fetching sentry-cli-Linux-x86_64 14%
fetching sentry-cli-Linux-x86_64 15%
fetching sentry-cli-Linux-x86_64 16%
fetching sentry-cli-Linux-x86_64 17%
fetching sentry-cli-Linux-x86_64 18%
fetching sentry-cli-Linux-x86_64 19%
fetching sentry-cli-Linux-x86_64 20%
fetching sentry-cli-Linux-x86_64 21%
fetching sentry-cli-Linux-x86_64 22%
fetching sentry-cli-Linux-x86_64 23%
fetching sentry-cli-Linux-x86_64 24%
fetching sentry-cli-Linux-x86_64 25%
fetching sentry-cli-Linux-x86_64 26%
fetching sentry-cli-Linux-x86_64 27%
fetching sentry-cli-Linux-x86_64 28%
fetching sentry-cli-Linux-x86_64 29%
fetching sentry-cli-Linux-x86_64 30%
fetching sentry-cli-Linux-x86_64 31%
fetching sentry-cli-Linux-x86_64 32%
fetching sentry-cli-Linux-x86_64 33%
fetching sentry-cli-Linux-x86_64 34%
fetching sentry-cli-Linux-x86_64 85%
fetching sentry-cli-Linux-x86_64 86%
fetching sentry-cli-Linux-x86_64 87%
fetching sentry-cli-Linux-x86_64 88%
fetching sentry-cli-Linux-x86_64 89%
fetching sentry-cli-Linux-x86_64 90%
fetching sentry-cli-Linux-x86_64 91%
fetching sentry-cli-Linux-x86_64 92%
fetching sentry-cli-Linux-x86_64 93%
fetching sentry-cli-Linux-x86_64 94%
fetching sentry-cli-Linux-x86_64 95%
fetching sentry-cli-Linux-x86_64 96%
fetching sentry-cli-Linux-x86_64 97%
fetching sentry-cli-Linux-x86_64 98%
fetching sentry-cli-Linux-x86_64 99%
fetching sentry-cli-Linux-x86_64 100%
Error: Command failed: /home/runner/work/smol/smol/customer-api/node_modules/@sentry/cli/sentry-cli --version
error: stream did not contain valid UTF-8
thread 'unnamed' panicked at 'Config not bound yet': src/config.rs:85

   0: sentry_cli::utils::system::init_backtrace::{{closure}}
   1: sentry::integrations::panic::register_panic_handler::{{closure}}
   2: std::panicking::rust_panic_with_hook
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:530
   3: rust_begin_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:437
   4: core::panicking::panic_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/panicking.rs:85
   5: core::option::expect_failed
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/option.rs:1261
   6: sentry_cli::config::Config::current
   7: sentry_cli::utils::system::print_error
   8: sentry_cli::commands::main


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sentry/cli@1.58.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @sentry/cli@1.58.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Here's the github action:

```yaml
jobs:
  customer-api:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1
        with:
          ref: ${{ github.head_ref }}

      - name: install
        uses: bahmutov/npm-install@v1.4.1
        with:
          working-directory: customer-api
```

Here are the relevant dependencies from my package.json:

```
"dependencies": {
    // ...
    "@sentry/integrations": "5.24.2",
    "@sentry/node": "5.24.2",
    // ...
  },
  "devDependencies": {
    // ...
    "@sentry/webpack-plugin": "1.13.0",
    // ...
    }
```

**Comment by kamilogorek** [comment]
Looks like some kind of hiccup to me. Just verified it on an empty repo and it works just fine - https://github.com/kamilogorek/tmp/runs/1187733612?check_suite_focus=true

**Comment by leemhenson** [comment]
I just tried it again, updating to the latest action version: `bahmutov/npm-install@v1.4.3` 

```
etching sentry-cli-Linux-x86_64 98%
fetching sentry-cli-Linux-x86_64 99%
fetching sentry-cli-Linux-x86_64 100%
Error: Command failed: /home/runner/work/smol/smol/customer-api/node_modules/@sentry/cli/sentry-cli --version
error: stream did not contain valid UTF-8
thread 'unnamed' panicked at 'Config not bound yet': src/config.rs:85

   0: sentry_cli::utils::system::init_backtrace::{{closure}}
   1: sentry::integrations::panic::register_panic_handler::{{closure}}
   2: std::panicking::rust_panic_with_hook
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:530
   3: rust_begin_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:437
   4: core::panicking::panic_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/panicking.rs:85
   5: core::option::expect_failed
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/option.rs:1261
   6: sentry_cli::config::Config::current
   7: sentry_cli::utils::system::print_error
   8: sentry_cli::commands::main


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sentry/cli@1.58.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @sentry/cli@1.58.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by superyarik** [comment]
same problem on CI server

**Comment by leemhenson** [comment]
Still broken for me too 😞 .

```
...
npm ERR! fetching sentry-cli-Linux-x86_64 99%
npm ERR! fetching sentry-cli-Linux-x86_64 100%
npm ERR! Error: Command failed: /home/runner/work/stuff-here/node_modules/@sentry/cli/sentry-cli --version
npm ERR! error: stream did not contain valid UTF-8
npm ERR! thread 'unnamed' panicked at 'Config not bound yet': src/config.rs:85
npm ERR! 
npm ERR!    0: sentry_cli::utils::system::init_backtrace::{{closure}}
npm ERR!    1: sentry::integrations::panic::register_panic_handler::{{closure}}
npm ERR!    2: std::panicking::rust_panic_with_hook
npm ERR!              at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:573
npm ERR!    3: std::panicking::begin_panic_handler::{{closure}}
npm ERR!              at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:476
npm ERR!    4: std::sys_common::backtrace::__rust_end_short_backtrace
npm ERR!              at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:153
npm ERR!    5: rust_begin_unwind
npm ERR!              at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
npm ERR!    6: core::panicking::panic_fmt
npm ERR!              at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
npm ERR!    7: core::option::expect_failed
npm ERR!              at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1213
npm ERR!    8: sentry_cli::config::Config::current
npm ERR!    9: sentry_cli::utils::system::print_error
npm ERR!   10: sentry_cli::commands::main
npm ERR!   11: std::sys_common::backtrace::__rust_begin_short_backtrace
npm ERR!   12: core::ops::function::FnOnce::call_once{{vtable.shim}}
npm ERR!   13: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
npm ERR!              at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/boxed.rs:1042
npm ERR!       <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
npm ERR!              at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/boxed.rs:1042
npm ERR!       std::sys::unix::thread::Thread::new::thread_start
npm ERR!              at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys/unix/thread.rs:87
```

**Comment by leemhenson** [comment]
I have no idea why it helped, but I moved `@sentry/cli` to optionalDependencies and now it does not fail to install. I think there must be a race condition of some sort in there.

**Comment by superyarik** [comment]
we have found problem - provider block some IPs and this IP used in sentry CDNs (i am from Russia)
151.101.194.217, 151.101.130.217, 151.101.66.217, 151.101.2.217 block by roskomnadzor - https://reestr.rublacklist.net/search/?q=151.101.2.217

**Comment by kamilogorek** [comment]
@superyarik if our CDN is blocked, it's possible to swap the CDN the script points to and use the GitHub itself instead.

```
SENTRYCLI_CDNURL=https://github.com/getsentry/sentry-cli/releases/download/ npm install @sentry/cli
```

**Comment by kamilogorek** [comment]
Closing the issue, as it seems like the original issue has been partially resolved or there is a working solution. I'd prefer someone to create a new issue with a fresh description if it's still an issue.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
