### ISSUE TITLE
Unable to install on node:7-alpine via NPM

### ISSUE THREAD

**Issue by arvalaan** [getsentry/sentry-cli#90]
```
npm i sentry-cli-binary
npm info it worked if it ends with ok
npm info using npm@4.2.0
npm info using node@v7.10.0
npm info attempt registry request try #1 at 10:23:03 AM
npm http request GET https://registry.npmjs.org/sentry-cli-binary
npm http 304 https://registry.npmjs.org/sentry-cli-binary
npm info addNameTag [ 'sentry-cli-binary', 'latest' ]
npm info attempt registry request try #1 at 10:23:05 AM
npm http request GET https://registry.npmjs.org/progress
npm http 304 https://registry.npmjs.org/progress
npm info attempt registry request try #1 at 10:23:07 AM
npm http request GET https://registry.npmjs.org/fsevents
npm http 304 https://registry.npmjs.org/fsevents
npm info lifecycle progress@2.0.0~preinstall: progress@2.0.0
npm info lifecycle sentry-cli-binary@1.16.0~preinstall: sentry-cli-binary@1.16.0
npm info linkStuff progress@2.0.0
npm info linkStuff sentry-cli-binary@1.16.0
npm info lifecycle progress@2.0.0~install: progress@2.0.0
npm info lifecycle sentry-cli-binary@1.16.0~install: sentry-cli-binary@1.16.0

> sentry-cli-binary@1.16.0 install /app/node_modules/sentry-cli-binary
> node ./bin/install-sentry-cli

fetching sentry-cli-Linux-x86_64 ████████████████████ 100% 0.0s
Something went wrong!
{ Error: Command failed: /app/node_modules/sentry-cli-binary/bin/../sentry-cli --version
/bin/sh: /app/node_modules/sentry-cli-binary/bin/../sentry-cli: not found

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)
  killed: false,
  code: 127,
  signal: null,
  cmd: '/app/node_modules/sentry-cli-binary/bin/../sentry-cli --version' }
npm info lifecycle sentry-cli-binary@1.16.0~install: Failed to exec install script
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN angular2-jwt@0.1.28 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN angular2-jwt@0.1.28 requires a peer of @angular/http@^2.0.0 but none was installed.
npm WARN ng2-select2@1.0.0-beta.10 requires a peer of @angular/core@^2.2.0 but none was installed.
npm ERR! Linux 4.9.30-rancher
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "sentry-cli-binary"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! sentry-cli-binary@1.16.0 install: `node ./bin/install-sentry-cli`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sentry-cli-binary@1.16.0 install script 'node ./bin/install-sentry-cli'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sentry-cli-binary package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/install-sentry-cli
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sentry-cli-binary
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sentry-cli-binary
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-06-29T10_23_24_313Z-debug.log
```

I've been trying to install Sentry-CLI on our CI Server with the Node Alpine image to keep it quick but am failing to do so. Any help would be appreciated!

**Comment by mitsuhiko** [comment]
Alpine linux is not supported. See #70
